checks:
    python:
        code_rating: true
        duplicate_code: true

build:
    dependencies:
        before:
            - sudo apt-get install -y python-software-properties
#            - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable  # qgis 2.10
            - sudo apt-get install -y software-properties-common
            - sudo add-apt-repository http://qgis.org/debian-ltr  # for QGIS LTR
            - sudo apt-get update
            - sudo apt-get install -y --force-yes git qgis python-qgis xvfb python-nose python-coverage pyflakes python-nosexcover python-scientific python-beautifulsoup

tools:
    pylint:
        python_version: '2'
        config_file: pylintrc
filter:
    excluded_paths:
        - '*/test/*'
        - 'safe_extras/*'
        - 'extras/*'
        - 'resources/*'
        - 'scripts/*'