#! /bin/bash

# Name of root dir and repository
RIABDIR="risk_in_a_box"
RIABREPO="AIFDR/$RIABDIR.git"

echo "---------------------------------------------------------"
echo "Installing Risk in a Box and all its dependencies."
echo "This will take a little while depending on"
echo "the internet speed."
echo
echo "In any case, now is great time to go get a cup of coffee!"
echo "---------------------------------------------------------"

echo "Installing Ubuntu packages for running Risk in a Box"
gpg --keyserver keyserver.ubuntu.com --recv 1F9ADD375CA44993
gpg --export --armor 1F9ADD375CA44993 | sudo apt-key add -
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get -qq update
sudo apt-get install -q -y qgis python-qgis
echo "Installing Ubuntu packages for development"
sudo apt-get install -y git subversion pep8 python-nose python-coverage python-numpy python-sphinx pyqt4-dev-tools

# To get the gui test suite to pass.
# FIXME (Ole): gdal version is currently hardwired
sudo apt-get install libgdal1-1.8.0-grass


if grep -q RIABQGIS ~/.bash_aliases
then
    echo "You already have RIABQGIS in your ~/.bash_aliases"
    source ~/.bash_aliases
else
    export RIABQGIS=`pwd`/$RIABDIR  # Make path available for this session

    echo Path to RIABQGIS is $RIABQGIS

    # Store it for future sessions
    echo "export RIABQGIS=$RIABQGIS" >> ~/.bash_aliases
    #echo 'alias risiko-activate="source $RIAB_HOME/riab_env/bin/activate;echo Risk In a Box virtual environment activated. Available commands are:; echo;echo risiko-test risiko-start risiko-stop risiko-clean risiko-upload risiko-populate risiko-uninstall;echo"' >> ~/.bash_aliases
    echo "Adding RIABQGIS path to your ~/.bash_aliases"
 fi

# Function to clone the git repositories
function checkup() {
  REPO="$1"
  WORKING_DIR="$2"
  BRANCH="$3"
  if [ -d "${WORKING_DIR}" ];
  then
      echo "Updating ${WORKING_DIR} from upstream"
      (cd "${WORKING_DIR}" && git pull)
  else
      echo "git@github.com:${REPO} ${WORKING_DIR}"
      echo "https://github.com/${REPO} ${WORKING_DIR}"
      echo "http://github.com/${REPO} ${WORKING_DIR}"
      git clone "git@github.com:${REPO}" "${WORKING_DIR}" || git clone "https://github.com/${REPO}" "${WORKING_DIR}" || git clone "http://github.com/${REPO}" "${WORKING_DIR}"
  fi

  pushd .
  cd $WORKING_DIR
  git fetch origin $BRANCH
  git checkout $BRANCH
  popd
}

echo "Downloading Risk in a Box"
checkup ${RIABREPO} ${RIABDIR} master

echo "Downloading test and demo data"
echo dir $RIABQGIS
pushd $RIABQGIS
make testdata
popd


echo
echo "Congratulations, you have installed Risk in a Box - QGIS"
echo
echo "To verify that the installation works, you can run the test suite"
echo "cd $RIABQGIS"
echo "make test"
