# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_dialog_base.ui'
#
# Created: Thu Jul 11 16:53:56 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BatchDialogBase(object):
    def setupUi(self, BatchDialogBase):
        BatchDialogBase.setObjectName(_fromUtf8("BatchDialogBase"))
        BatchDialogBase.resize(455, 601)
        self.gridLayout_2 = QtGui.QGridLayout(BatchDialogBase)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scenarioDirLabel = QtGui.QLabel(BatchDialogBase)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scenarioDirLabel.setFont(font)
        self.scenarioDirLabel.setObjectName(_fromUtf8("scenarioDirLabel"))
        self.gridLayout_2.addWidget(self.scenarioDirLabel, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.leSourceDir = QtGui.QLineEdit(BatchDialogBase)
        self.leSourceDir.setEnabled(False)
        self.leSourceDir.setObjectName(_fromUtf8("leSourceDir"))
        self.horizontalLayout_4.addWidget(self.leSourceDir)
        self.toolSourceDir = QtGui.QToolButton(BatchDialogBase)
        self.toolSourceDir.setObjectName(_fromUtf8("toolSourceDir"))
        self.horizontalLayout_4.addWidget(self.toolSourceDir)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.resultTableLabel = QtGui.QLabel(BatchDialogBase)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultTableLabel.setFont(font)
        self.resultTableLabel.setObjectName(_fromUtf8("resultTableLabel"))
        self.gridLayout_2.addWidget(self.resultTableLabel, 2, 0, 1, 1)
        self.tblScript = QtGui.QTableWidget(BatchDialogBase)
        self.tblScript.setAlternatingRowColors(False)
        self.tblScript.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblScript.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblScript.setCornerButtonEnabled(False)
        self.tblScript.setObjectName(_fromUtf8("tblScript"))
        self.tblScript.setColumnCount(2)
        self.tblScript.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblScript.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblScript.setHorizontalHeaderItem(1, item)
        self.tblScript.horizontalHeader().setDefaultSectionSize(100)
        self.gridLayout_2.addWidget(self.tblScript, 3, 0, 1, 1)
        self.pbnAdvanced = QtGui.QPushButton(BatchDialogBase)
        self.pbnAdvanced.setCheckable(True)
        self.pbnAdvanced.setChecked(False)
        self.pbnAdvanced.setObjectName(_fromUtf8("pbnAdvanced"))
        self.gridLayout_2.addWidget(self.pbnAdvanced, 4, 0, 1, 1)
        self.gboOptions = QtGui.QGroupBox(BatchDialogBase)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gboOptions.setFont(font)
        self.gboOptions.setCheckable(False)
        self.gboOptions.setObjectName(_fromUtf8("gboOptions"))
        self.gridLayout = QtGui.QGridLayout(self.gboOptions)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.gboOptions)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.sboCount = QtGui.QSpinBox(self.gboOptions)
        self.sboCount.setSuffix(_fromUtf8(""))
        self.sboCount.setPrefix(_fromUtf8(""))
        self.sboCount.setMinimum(1)
        self.sboCount.setObjectName(_fromUtf8("sboCount"))
        self.horizontalLayout_2.addWidget(self.sboCount)
        self.label_2 = QtGui.QLabel(self.gboOptions)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.outputPDFDirLabel = QtGui.QLabel(self.gboOptions)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.outputPDFDirLabel.setFont(font)
        self.outputPDFDirLabel.setObjectName(_fromUtf8("outputPDFDirLabel"))
        self.verticalLayout.addWidget(self.outputPDFDirLabel)
        self.cbDefaultOutputDir = QtGui.QCheckBox(self.gboOptions)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbDefaultOutputDir.setFont(font)
        self.cbDefaultOutputDir.setChecked(True)
        self.cbDefaultOutputDir.setObjectName(_fromUtf8("cbDefaultOutputDir"))
        self.verticalLayout.addWidget(self.cbDefaultOutputDir)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.leOutputDir = QtGui.QLineEdit(self.gboOptions)
        self.leOutputDir.setEnabled(False)
        self.leOutputDir.setReadOnly(False)
        self.leOutputDir.setObjectName(_fromUtf8("leOutputDir"))
        self.horizontalLayout_3.addWidget(self.leOutputDir)
        self.toolOutputDir = QtGui.QToolButton(self.gboOptions)
        self.toolOutputDir.setEnabled(False)
        self.toolOutputDir.setObjectName(_fromUtf8("toolOutputDir"))
        self.horizontalLayout_3.addWidget(self.toolOutputDir)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gboOptions, 5, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(BatchDialogBase)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Yes|QtGui.QDialogButtonBox.YesToAll)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 6, 0, 1, 1)

        self.retranslateUi(BatchDialogBase)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), BatchDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(BatchDialogBase)

    def retranslateUi(self, BatchDialogBase):
        BatchDialogBase.setWindowTitle(_translate("BatchDialogBase", "Dialog", None))
        self.scenarioDirLabel.setText(_translate("BatchDialogBase", "Scenario directory", None))
        self.toolSourceDir.setText(_translate("BatchDialogBase", "...", None))
        self.resultTableLabel.setText(_translate("BatchDialogBase", "Result table", None))
        item = self.tblScript.horizontalHeaderItem(0)
        item.setText(_translate("BatchDialogBase", "Task", None))
        item = self.tblScript.horizontalHeaderItem(1)
        item.setText(_translate("BatchDialogBase", "Status", None))
        self.pbnAdvanced.setText(_translate("BatchDialogBase", "Show advanced options", None))
        self.gboOptions.setTitle(_translate("BatchDialogBase", "Advanced options", None))
        self.label.setText(_translate("BatchDialogBase", "Run selected script ", None))
        self.label_2.setText(_translate("BatchDialogBase", "times", None))
        self.outputPDFDirLabel.setText(_translate("BatchDialogBase", "Output PDF direcotry", None))
        self.cbDefaultOutputDir.setText(_translate("BatchDialogBase", "Use scenario directory", None))
        self.toolOutputDir.setText(_translate("BatchDialogBase", "...", None))

