# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dock_base.ui'
#
# Created: Sun Apr 27 22:51:17 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockBase(object):
    def setupUi(self, DockBase):
        DockBase.setObjectName(_fromUtf8("DockBase"))
        DockBase.resize(393, 668)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DockBase.setWindowIcon(icon)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pbnShowQuestion = QtGui.QPushButton(self.dockWidgetContents)
        self.pbnShowQuestion.setObjectName(_fromUtf8("pbnShowQuestion"))
        self.gridLayout.addWidget(self.pbnShowQuestion, 0, 0, 1, 1)
        self.grpQuestion = QtGui.QGroupBox(self.dockWidgetContents)
        self.grpQuestion.setObjectName(_fromUtf8("grpQuestion"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpQuestion)
        self.gridLayout_3.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.grpQuestion)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.cboHazard = QtGui.QComboBox(self.grpQuestion)
        self.cboHazard.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cboHazard.setObjectName(_fromUtf8("cboHazard"))
        self.gridLayout_3.addWidget(self.cboHazard, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.grpQuestion)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 6, 0, 1, 1)
        self.cboAggregation = QtGui.QComboBox(self.grpQuestion)
        self.cboAggregation.setObjectName(_fromUtf8("cboAggregation"))
        self.gridLayout_3.addWidget(self.cboAggregation, 7, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.grpQuestion)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.cboExposure = QtGui.QComboBox(self.grpQuestion)
        self.cboExposure.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cboExposure.setObjectName(_fromUtf8("cboExposure"))
        self.gridLayout_3.addWidget(self.cboExposure, 3, 0, 1, 2)
        self.cboFunction = QtGui.QComboBox(self.grpQuestion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFunction.sizePolicy().hasHeightForWidth())
        self.cboFunction.setSizePolicy(sizePolicy)
        self.cboFunction.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cboFunction.setObjectName(_fromUtf8("cboFunction"))
        self.gridLayout_3.addWidget(self.cboFunction, 5, 0, 1, 1)
        self.toolFunctionOptions = QtGui.QPushButton(self.grpQuestion)
        self.toolFunctionOptions.setEnabled(False)
        self.toolFunctionOptions.setObjectName(_fromUtf8("toolFunctionOptions"))
        self.gridLayout_3.addWidget(self.toolFunctionOptions, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.grpQuestion, 1, 0, 1, 1)
        self.wvResults = MessageViewer(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wvResults.sizePolicy().hasHeightForWidth())
        self.wvResults.setSizePolicy(sizePolicy)
        self.wvResults.setMinimumSize(QtCore.QSize(0, 50))
        self.wvResults.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.wvResults.setObjectName(_fromUtf8("wvResults"))
        self.gridLayout.addWidget(self.wvResults, 2, 0, 1, 1)
        self.org_logo_placeholder = QtGui.QHBoxLayout()
        self.org_logo_placeholder.setSpacing(0)
        self.org_logo_placeholder.setObjectName(_fromUtf8("org_logo_placeholder"))
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.org_logo_placeholder.addItem(spacerItem)
        self.organisation_logo = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.organisation_logo.sizePolicy().hasHeightForWidth())
        self.organisation_logo.setSizePolicy(sizePolicy)
        self.organisation_logo.setMaximumSize(QtCore.QSize(0, 64))
        self.organisation_logo.setText(_fromUtf8(""))
        self.organisation_logo.setScaledContents(True)
        self.organisation_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.organisation_logo.setObjectName(_fromUtf8("organisation_logo"))
        self.org_logo_placeholder.addWidget(self.organisation_logo)
        spacerItem1 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.org_logo_placeholder.addItem(spacerItem1)
        self.gridLayout.addLayout(self.org_logo_placeholder, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbnHelp = QtGui.QPushButton(self.dockWidgetContents)
        self.pbnHelp.setObjectName(_fromUtf8("pbnHelp"))
        self.horizontalLayout.addWidget(self.pbnHelp)
        spacerItem2 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.about_button = QtGui.QPushButton(self.dockWidgetContents)
        self.about_button.setObjectName(_fromUtf8("about_button"))
        self.horizontalLayout.addWidget(self.about_button)
        spacerItem3 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pbnPrint = QtGui.QPushButton(self.dockWidgetContents)
        self.pbnPrint.setObjectName(_fromUtf8("pbnPrint"))
        self.horizontalLayout.addWidget(self.pbnPrint)
        spacerItem4 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pbnRunStop = QtGui.QPushButton(self.dockWidgetContents)
        self.pbnRunStop.setObjectName(_fromUtf8("pbnRunStop"))
        self.horizontalLayout.addWidget(self.pbnRunStop)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        DockBase.setWidget(self.dockWidgetContents)
        self.label_8.setBuddy(self.cboFunction)
        self.label_7.setBuddy(self.cboExposure)

        self.retranslateUi(DockBase)
        QtCore.QObject.connect(self.pbnShowQuestion, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pbnShowQuestion.hide)
        QtCore.QObject.connect(self.pbnShowQuestion, QtCore.SIGNAL(_fromUtf8("clicked()")), self.grpQuestion.show)
        QtCore.QMetaObject.connectSlotsByName(DockBase)
        DockBase.setTabOrder(self.pbnShowQuestion, self.cboHazard)
        DockBase.setTabOrder(self.cboHazard, self.cboExposure)
        DockBase.setTabOrder(self.cboExposure, self.cboFunction)
        DockBase.setTabOrder(self.cboFunction, self.toolFunctionOptions)
        DockBase.setTabOrder(self.toolFunctionOptions, self.cboAggregation)
        DockBase.setTabOrder(self.cboAggregation, self.pbnHelp)
        DockBase.setTabOrder(self.pbnHelp, self.about_button)
        DockBase.setTabOrder(self.about_button, self.pbnPrint)
        DockBase.setTabOrder(self.pbnPrint, self.pbnRunStop)

    def retranslateUi(self, DockBase):
        DockBase.setWindowTitle(_translate("DockBase", "InaSAFE", None))
        self.pbnShowQuestion.setText(_translate("DockBase", "Show question form", None))
        self.grpQuestion.setTitle(_translate("DockBase", "Question: In the event of", None))
        self.label_8.setText(_translate("DockBase", "&Might", None))
        self.label_2.setText(_translate("DockBase", "Aggregate results by", None))
        self.label_7.setText(_translate("DockBase", "How many", None))
        self.toolFunctionOptions.setText(_translate("DockBase", "Options ...", None))
        self.pbnHelp.setText(_translate("DockBase", "Help", None))
        self.about_button.setText(_translate("DockBase", "About", None))
        self.pbnPrint.setText(_translate("DockBase", "Print ...", None))
        self.pbnRunStop.setText(_translate("DockBase", "Run", None))

from ..widgets.message_viewer import MessageViewer
import resources_rc
