# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function_browser_dialog_base.ui'
#
# Created: Thu Nov 27 10:20:50 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FunctionBrowserDialogBase(object):
    def setupUi(self, FunctionBrowserDialogBase):
        FunctionBrowserDialogBase.setObjectName(_fromUtf8("FunctionBrowserDialogBase"))
        FunctionBrowserDialogBase.resize(821, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FunctionBrowserDialogBase.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(FunctionBrowserDialogBase)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.myButtonBox = QtGui.QDialogButtonBox(FunctionBrowserDialogBase)
        self.myButtonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.myButtonBox.setAutoFillBackground(False)
        self.myButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.myButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Reset)
        self.myButtonBox.setCenterButtons(False)
        self.myButtonBox.setObjectName(_fromUtf8("myButtonBox"))
        self.gridLayout.addWidget(self.myButtonBox, 1, 1, 1, 1)
        self.gridLayoutMain = QtGui.QGridLayout()
        self.gridLayoutMain.setHorizontalSpacing(0)
        self.gridLayoutMain.setObjectName(_fromUtf8("gridLayoutMain"))
        self.label_title = QtGui.QLabel(FunctionBrowserDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.gridLayoutMain.addWidget(self.label_title, 1, 0, 1, 1)
        self.label_id = QtGui.QLabel(FunctionBrowserDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_id.sizePolicy().hasHeightForWidth())
        self.label_id.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_id.setFont(font)
        self.label_id.setObjectName(_fromUtf8("label_id"))
        self.gridLayoutMain.addWidget(self.label_id, 1, 1, 1, 1)
        self.label_subcategory = QtGui.QLabel(FunctionBrowserDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_subcategory.sizePolicy().hasHeightForWidth())
        self.label_subcategory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_subcategory.setFont(font)
        self.label_subcategory.setObjectName(_fromUtf8("label_subcategory"))
        self.gridLayoutMain.addWidget(self.label_subcategory, 1, 3, 1, 1)
        self.label_category = QtGui.QLabel(FunctionBrowserDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_category.sizePolicy().hasHeightForWidth())
        self.label_category.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_category.setFont(font)
        self.label_category.setObjectName(_fromUtf8("label_category"))
        self.gridLayoutMain.addWidget(self.label_category, 1, 2, 1, 1)
        self.label_layertype = QtGui.QLabel(FunctionBrowserDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_layertype.sizePolicy().hasHeightForWidth())
        self.label_layertype.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_layertype.setFont(font)
        self.label_layertype.setObjectName(_fromUtf8("label_layertype"))
        self.gridLayoutMain.addWidget(self.label_layertype, 1, 4, 1, 1)
        self.comboBox_id = QtGui.QComboBox(FunctionBrowserDialogBase)
        self.comboBox_id.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_id.setObjectName(_fromUtf8("comboBox_id"))
        self.gridLayoutMain.addWidget(self.comboBox_id, 3, 1, 1, 1)
        self.comboBox_title = QtGui.QComboBox(FunctionBrowserDialogBase)
        self.comboBox_title.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_title.setMinimumContentsLength(0)
        self.comboBox_title.setObjectName(_fromUtf8("comboBox_title"))
        self.gridLayoutMain.addWidget(self.comboBox_title, 3, 0, 1, 1)
        self.comboBox_category = QtGui.QComboBox(FunctionBrowserDialogBase)
        self.comboBox_category.setObjectName(_fromUtf8("comboBox_category"))
        self.gridLayoutMain.addWidget(self.comboBox_category, 3, 2, 1, 1)
        self.label_unit = QtGui.QLabel(FunctionBrowserDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_unit.sizePolicy().hasHeightForWidth())
        self.label_unit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_unit.setFont(font)
        self.label_unit.setObjectName(_fromUtf8("label_unit"))
        self.gridLayoutMain.addWidget(self.label_unit, 1, 6, 1, 1)
        self.label_datatype = QtGui.QLabel(FunctionBrowserDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_datatype.sizePolicy().hasHeightForWidth())
        self.label_datatype.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_datatype.setFont(font)
        self.label_datatype.setObjectName(_fromUtf8("label_datatype"))
        self.gridLayoutMain.addWidget(self.label_datatype, 1, 5, 1, 1)
        self.comboBox_subcategory = QtGui.QComboBox(FunctionBrowserDialogBase)
        self.comboBox_subcategory.setObjectName(_fromUtf8("comboBox_subcategory"))
        self.gridLayoutMain.addWidget(self.comboBox_subcategory, 3, 3, 1, 1)
        self.comboBox_layertype = QtGui.QComboBox(FunctionBrowserDialogBase)
        self.comboBox_layertype.setObjectName(_fromUtf8("comboBox_layertype"))
        self.gridLayoutMain.addWidget(self.comboBox_layertype, 3, 4, 1, 1)
        self.comboBox_datatype = QtGui.QComboBox(FunctionBrowserDialogBase)
        self.comboBox_datatype.setObjectName(_fromUtf8("comboBox_datatype"))
        self.gridLayoutMain.addWidget(self.comboBox_datatype, 3, 5, 1, 1)
        self.comboBox_unit = QtGui.QComboBox(FunctionBrowserDialogBase)
        self.comboBox_unit.setObjectName(_fromUtf8("comboBox_unit"))
        self.gridLayoutMain.addWidget(self.comboBox_unit, 3, 6, 1, 1)
        self.webView = QtWebKit.QWebView(FunctionBrowserDialogBase)
        self.webView.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.gridLayoutMain.addWidget(self.webView, 4, 0, 1, 7)
        self.gridLayout.addLayout(self.gridLayoutMain, 0, 1, 1, 1)

        self.retranslateUi(FunctionBrowserDialogBase)
        QtCore.QObject.connect(self.myButtonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), FunctionBrowserDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(FunctionBrowserDialogBase)

    def retranslateUi(self, FunctionBrowserDialogBase):
        FunctionBrowserDialogBase.setWindowTitle(_translate("FunctionBrowserDialogBase", "InaSAFE Impact Functions", None))
        self.label_title.setText(_translate("FunctionBrowserDialogBase", "Title", None))
        self.label_id.setText(_translate("FunctionBrowserDialogBase", "ID", None))
        self.label_subcategory.setText(_translate("FunctionBrowserDialogBase", "Subcategory", None))
        self.label_category.setText(_translate("FunctionBrowserDialogBase", "Category", None))
        self.label_layertype.setText(_translate("FunctionBrowserDialogBase", "Layer Type", None))
        self.label_unit.setText(_translate("FunctionBrowserDialogBase", "Unit", None))
        self.label_datatype.setText(_translate("FunctionBrowserDialogBase", "Data Type", None))

from PyQt4 import QtWebKit
import resources_rc
