# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keywords_dialog_base.ui'
#
# Created: Fri Jun  6 14:15:26 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_KeywordsDialogBase(object):
    def setupUi(self, KeywordsDialogBase):
        KeywordsDialogBase.setObjectName(_fromUtf8("KeywordsDialogBase"))
        KeywordsDialogBase.resize(630, 425)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(KeywordsDialogBase.sizePolicy().hasHeightForWidth())
        KeywordsDialogBase.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        KeywordsDialogBase.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(KeywordsDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblLayerName = QtGui.QLabel(KeywordsDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLayerName.sizePolicy().hasHeightForWidth())
        self.lblLayerName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLayerName.setFont(font)
        self.lblLayerName.setText(_fromUtf8(""))
        self.lblLayerName.setWordWrap(True)
        self.lblLayerName.setObjectName(_fromUtf8("lblLayerName"))
        self.verticalLayout.addWidget(self.lblLayerName)
        self.scrollArea = QtGui.QScrollArea(KeywordsDialogBase)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 595, 845))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grpSimple = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpSimple.sizePolicy().hasHeightForWidth())
        self.grpSimple.setSizePolicy(sizePolicy)
        self.grpSimple.setObjectName(_fromUtf8("grpSimple"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpSimple)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cboElderlyRatioAttribute = QtGui.QComboBox(self.grpSimple)
        self.cboElderlyRatioAttribute.setObjectName(_fromUtf8("cboElderlyRatioAttribute"))
        self.gridLayout_2.addWidget(self.cboElderlyRatioAttribute, 13, 2, 1, 1)
        self.leSource = QtGui.QLineEdit(self.grpSimple)
        self.leSource.setDragEnabled(True)
        self.leSource.setObjectName(_fromUtf8("leSource"))
        self.gridLayout_2.addWidget(self.leSource, 2, 2, 1, 1)
        self.lblAggregationAttribute = QtGui.QLabel(self.grpSimple)
        self.lblAggregationAttribute.setEnabled(True)
        self.lblAggregationAttribute.setObjectName(_fromUtf8("lblAggregationAttribute"))
        self.gridLayout_2.addWidget(self.lblAggregationAttribute, 6, 0, 1, 2)
        self.cboAggregationAttribute = QtGui.QComboBox(self.grpSimple)
        self.cboAggregationAttribute.setObjectName(_fromUtf8("cboAggregationAttribute"))
        self.gridLayout_2.addWidget(self.cboAggregationAttribute, 6, 2, 1, 1)
        self.cboSubcategory = QtGui.QComboBox(self.grpSimple)
        self.cboSubcategory.setObjectName(_fromUtf8("cboSubcategory"))
        self.gridLayout_2.addWidget(self.cboSubcategory, 5, 2, 1, 1)
        self.lblFemaleRatioAttribute = QtGui.QLabel(self.grpSimple)
        self.lblFemaleRatioAttribute.setObjectName(_fromUtf8("lblFemaleRatioAttribute"))
        self.gridLayout_2.addWidget(self.lblFemaleRatioAttribute, 7, 0, 1, 2)
        self.lblSubcategory = QtGui.QLabel(self.grpSimple)
        self.lblSubcategory.setObjectName(_fromUtf8("lblSubcategory"))
        self.gridLayout_2.addWidget(self.lblSubcategory, 5, 0, 1, 1)
        self.lblFemaleRatioDefault = QtGui.QLabel(self.grpSimple)
        self.lblFemaleRatioDefault.setObjectName(_fromUtf8("lblFemaleRatioDefault"))
        self.gridLayout_2.addWidget(self.lblFemaleRatioDefault, 8, 0, 1, 1)
        self.lblSource = QtGui.QLabel(self.grpSimple)
        self.lblSource.setObjectName(_fromUtf8("lblSource"))
        self.gridLayout_2.addWidget(self.lblSource, 2, 0, 1, 1)
        self.dsbFemaleRatioDefault = QtGui.QDoubleSpinBox(self.grpSimple)
        self.dsbFemaleRatioDefault.setAccelerated(True)
        self.dsbFemaleRatioDefault.setMaximum(1.0)
        self.dsbFemaleRatioDefault.setSingleStep(0.01)
        self.dsbFemaleRatioDefault.setProperty("value", 0.0)
        self.dsbFemaleRatioDefault.setObjectName(_fromUtf8("dsbFemaleRatioDefault"))
        self.gridLayout_2.addWidget(self.dsbFemaleRatioDefault, 8, 2, 1, 1)
        self.cboFemaleRatioAttribute = QtGui.QComboBox(self.grpSimple)
        self.cboFemaleRatioAttribute.setObjectName(_fromUtf8("cboFemaleRatioAttribute"))
        self.gridLayout_2.addWidget(self.cboFemaleRatioAttribute, 7, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radHazard = QtGui.QRadioButton(self.grpSimple)
        self.radHazard.setObjectName(_fromUtf8("radHazard"))
        self.horizontalLayout_3.addWidget(self.radHazard)
        self.radExposure = QtGui.QRadioButton(self.grpSimple)
        self.radExposure.setChecked(True)
        self.radExposure.setObjectName(_fromUtf8("radExposure"))
        self.horizontalLayout_3.addWidget(self.radExposure)
        self.radPostprocessing = QtGui.QRadioButton(self.grpSimple)
        self.radPostprocessing.setObjectName(_fromUtf8("radPostprocessing"))
        self.horizontalLayout_3.addWidget(self.radPostprocessing)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 2, 1, 1)
        self.lblTitle = QtGui.QLabel(self.grpSimple)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gridLayout_2.addWidget(self.lblTitle, 1, 0, 1, 1)
        self.lblCategory = QtGui.QLabel(self.grpSimple)
        self.lblCategory.setObjectName(_fromUtf8("lblCategory"))
        self.gridLayout_2.addWidget(self.lblCategory, 4, 0, 1, 1)
        self.leTitle = QtGui.QLineEdit(self.grpSimple)
        self.leTitle.setObjectName(_fromUtf8("leTitle"))
        self.gridLayout_2.addWidget(self.leTitle, 1, 2, 1, 1)
        self.dsbAdultRatioDefault = QtGui.QDoubleSpinBox(self.grpSimple)
        self.dsbAdultRatioDefault.setMaximum(1.0)
        self.dsbAdultRatioDefault.setSingleStep(0.01)
        self.dsbAdultRatioDefault.setObjectName(_fromUtf8("dsbAdultRatioDefault"))
        self.gridLayout_2.addWidget(self.dsbAdultRatioDefault, 12, 2, 1, 1)
        self.cboYouthRatioAttribute = QtGui.QComboBox(self.grpSimple)
        self.cboYouthRatioAttribute.setObjectName(_fromUtf8("cboYouthRatioAttribute"))
        self.gridLayout_2.addWidget(self.cboYouthRatioAttribute, 9, 2, 1, 1)
        self.dsbYouthRatioDefault = QtGui.QDoubleSpinBox(self.grpSimple)
        self.dsbYouthRatioDefault.setMaximum(1.0)
        self.dsbYouthRatioDefault.setSingleStep(0.01)
        self.dsbYouthRatioDefault.setObjectName(_fromUtf8("dsbYouthRatioDefault"))
        self.gridLayout_2.addWidget(self.dsbYouthRatioDefault, 10, 2, 1, 1)
        self.cboAdultRatioAttribute = QtGui.QComboBox(self.grpSimple)
        self.cboAdultRatioAttribute.setObjectName(_fromUtf8("cboAdultRatioAttribute"))
        self.gridLayout_2.addWidget(self.cboAdultRatioAttribute, 11, 2, 1, 1)
        self.dsbElderlyRatioDefault = QtGui.QDoubleSpinBox(self.grpSimple)
        self.dsbElderlyRatioDefault.setMaximum(1.0)
        self.dsbElderlyRatioDefault.setSingleStep(0.01)
        self.dsbElderlyRatioDefault.setObjectName(_fromUtf8("dsbElderlyRatioDefault"))
        self.gridLayout_2.addWidget(self.dsbElderlyRatioDefault, 14, 2, 1, 1)
        self.lblElderlyRatioDefault = QtGui.QLabel(self.grpSimple)
        self.lblElderlyRatioDefault.setObjectName(_fromUtf8("lblElderlyRatioDefault"))
        self.gridLayout_2.addWidget(self.lblElderlyRatioDefault, 14, 0, 1, 1)
        self.lblElderlyRatioAttribute = QtGui.QLabel(self.grpSimple)
        self.lblElderlyRatioAttribute.setObjectName(_fromUtf8("lblElderlyRatioAttribute"))
        self.gridLayout_2.addWidget(self.lblElderlyRatioAttribute, 13, 0, 1, 1)
        self.lblAdultRatioDefault = QtGui.QLabel(self.grpSimple)
        self.lblAdultRatioDefault.setObjectName(_fromUtf8("lblAdultRatioDefault"))
        self.gridLayout_2.addWidget(self.lblAdultRatioDefault, 12, 0, 1, 1)
        self.lblAdultRatioAttribute = QtGui.QLabel(self.grpSimple)
        self.lblAdultRatioAttribute.setObjectName(_fromUtf8("lblAdultRatioAttribute"))
        self.gridLayout_2.addWidget(self.lblAdultRatioAttribute, 11, 0, 1, 1)
        self.lblYouthRatioDefault = QtGui.QLabel(self.grpSimple)
        self.lblYouthRatioDefault.setObjectName(_fromUtf8("lblYouthRatioDefault"))
        self.gridLayout_2.addWidget(self.lblYouthRatioDefault, 10, 0, 1, 1)
        self.lblYouthRatioAttribute = QtGui.QLabel(self.grpSimple)
        self.lblYouthRatioAttribute.setObjectName(_fromUtf8("lblYouthRatioAttribute"))
        self.gridLayout_2.addWidget(self.lblYouthRatioAttribute, 9, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.grpSimple)
        self.pbnAdvanced = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pbnAdvanced.setCheckable(True)
        self.pbnAdvanced.setObjectName(_fromUtf8("pbnAdvanced"))
        self.verticalLayout_2.addWidget(self.pbnAdvanced)
        self.grpAdvanced = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpAdvanced.sizePolicy().hasHeightForWidth())
        self.grpAdvanced.setSizePolicy(sizePolicy)
        self.grpAdvanced.setObjectName(_fromUtf8("grpAdvanced"))
        self.gridLayout = QtGui.QGridLayout(self.grpAdvanced)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.radPredefined = QtGui.QRadioButton(self.grpAdvanced)
        self.radPredefined.setObjectName(_fromUtf8("radPredefined"))
        self.horizontalLayout_4.addWidget(self.radPredefined)
        self.radUserDefined = QtGui.QRadioButton(self.grpAdvanced)
        self.radUserDefined.setObjectName(_fromUtf8("radUserDefined"))
        self.horizontalLayout_4.addWidget(self.radUserDefined)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.framePredefined = QtGui.QFrame(self.grpAdvanced)
        self.framePredefined.setFrameShape(QtGui.QFrame.StyledPanel)
        self.framePredefined.setFrameShadow(QtGui.QFrame.Raised)
        self.framePredefined.setObjectName(_fromUtf8("framePredefined"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.framePredefined)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.framePredefined)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.cboKeyword = QtGui.QComboBox(self.framePredefined)
        self.cboKeyword.setObjectName(_fromUtf8("cboKeyword"))
        self.cboKeyword.addItem(_fromUtf8(""))
        self.cboKeyword.setItemText(0, _fromUtf8("subcategory"))
        self.cboKeyword.addItem(_fromUtf8(""))
        self.cboKeyword.setItemText(1, _fromUtf8("unit"))
        self.cboKeyword.addItem(_fromUtf8(""))
        self.cboKeyword.setItemText(2, _fromUtf8("datatype"))
        self.cboKeyword.addItem(_fromUtf8(""))
        self.cboKeyword.setItemText(3, _fromUtf8("key_attribute"))
        self.horizontalLayout.addWidget(self.cboKeyword)
        self.label_5 = QtGui.QLabel(self.framePredefined)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lePredefinedValue = QtGui.QLineEdit(self.framePredefined)
        self.lePredefinedValue.setObjectName(_fromUtf8("lePredefinedValue"))
        self.horizontalLayout.addWidget(self.lePredefinedValue)
        self.pbnAddToList1 = QtGui.QPushButton(self.framePredefined)
        self.pbnAddToList1.setObjectName(_fromUtf8("pbnAddToList1"))
        self.horizontalLayout.addWidget(self.pbnAddToList1)
        self.gridLayout.addWidget(self.framePredefined, 1, 0, 1, 1)
        self.frameUserDefined = QtGui.QFrame(self.grpAdvanced)
        self.frameUserDefined.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameUserDefined.setFrameShadow(QtGui.QFrame.Raised)
        self.frameUserDefined.setObjectName(_fromUtf8("frameUserDefined"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frameUserDefined)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.frameUserDefined)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.leKey = QtGui.QLineEdit(self.frameUserDefined)
        self.leKey.setObjectName(_fromUtf8("leKey"))
        self.horizontalLayout_2.addWidget(self.leKey)
        self.label_7 = QtGui.QLabel(self.frameUserDefined)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.leValue = QtGui.QLineEdit(self.frameUserDefined)
        self.leValue.setObjectName(_fromUtf8("leValue"))
        self.horizontalLayout_2.addWidget(self.leValue)
        self.pbnAddToList2 = QtGui.QPushButton(self.frameUserDefined)
        self.pbnAddToList2.setObjectName(_fromUtf8("pbnAddToList2"))
        self.horizontalLayout_2.addWidget(self.pbnAddToList2)
        self.gridLayout.addWidget(self.frameUserDefined, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.grpAdvanced)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.lstKeywords = QtGui.QListWidget(self.grpAdvanced)
        self.lstKeywords.setAlternatingRowColors(True)
        self.lstKeywords.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lstKeywords.setObjectName(_fromUtf8("lstKeywords"))
        self.gridLayout.addWidget(self.lstKeywords, 4, 0, 1, 1)
        self.lblMessage = QtGui.QLabel(self.grpAdvanced)
        self.lblMessage.setStyleSheet(_fromUtf8("color: red;"))
        self.lblMessage.setText(_fromUtf8(""))
        self.lblMessage.setTextFormat(QtCore.Qt.RichText)
        self.lblMessage.setWordWrap(True)
        self.lblMessage.setObjectName(_fromUtf8("lblMessage"))
        self.gridLayout.addWidget(self.lblMessage, 5, 0, 1, 1)
        self.pbnRemove = QtGui.QPushButton(self.grpAdvanced)
        self.pbnRemove.setObjectName(_fromUtf8("pbnRemove"))
        self.gridLayout.addWidget(self.pbnRemove, 6, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.grpAdvanced)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtGui.QDialogButtonBox(KeywordsDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblAggregationAttribute.setBuddy(self.cboAggregationAttribute)
        self.lblFemaleRatioAttribute.setBuddy(self.cboFemaleRatioAttribute)
        self.lblSubcategory.setBuddy(self.cboSubcategory)
        self.lblFemaleRatioDefault.setBuddy(self.dsbFemaleRatioDefault)
        self.lblSource.setBuddy(self.leSource)
        self.lblTitle.setBuddy(self.leTitle)
        self.lblCategory.setBuddy(self.radHazard)
        self.lblElderlyRatioDefault.setBuddy(self.dsbElderlyRatioDefault)
        self.lblElderlyRatioAttribute.setBuddy(self.cboElderlyRatioAttribute)
        self.lblAdultRatioDefault.setBuddy(self.dsbAdultRatioDefault)
        self.lblAdultRatioAttribute.setBuddy(self.cboAdultRatioAttribute)
        self.lblYouthRatioDefault.setBuddy(self.dsbYouthRatioDefault)
        self.lblYouthRatioAttribute.setBuddy(self.cboYouthRatioAttribute)
        self.label_4.setBuddy(self.cboKeyword)
        self.label_6.setBuddy(self.leKey)
        self.label_7.setBuddy(self.leValue)
        self.label_8.setBuddy(self.lstKeywords)

        self.retranslateUi(KeywordsDialogBase)
        QtCore.QObject.connect(self.radPredefined, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frameUserDefined.setHidden)
        QtCore.QObject.connect(self.radUserDefined, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.framePredefined.setHidden)
        QtCore.QObject.connect(self.radPredefined, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.framePredefined.setVisible)
        QtCore.QObject.connect(self.radUserDefined, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frameUserDefined.setVisible)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), KeywordsDialogBase.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), KeywordsDialogBase.accept)
        QtCore.QMetaObject.connectSlotsByName(KeywordsDialogBase)
        KeywordsDialogBase.setTabOrder(self.leTitle, self.leSource)
        KeywordsDialogBase.setTabOrder(self.leSource, self.radHazard)
        KeywordsDialogBase.setTabOrder(self.radHazard, self.radExposure)
        KeywordsDialogBase.setTabOrder(self.radExposure, self.radPostprocessing)
        KeywordsDialogBase.setTabOrder(self.radPostprocessing, self.cboSubcategory)
        KeywordsDialogBase.setTabOrder(self.cboSubcategory, self.cboAggregationAttribute)
        KeywordsDialogBase.setTabOrder(self.cboAggregationAttribute, self.cboFemaleRatioAttribute)
        KeywordsDialogBase.setTabOrder(self.cboFemaleRatioAttribute, self.dsbFemaleRatioDefault)
        KeywordsDialogBase.setTabOrder(self.dsbFemaleRatioDefault, self.cboYouthRatioAttribute)
        KeywordsDialogBase.setTabOrder(self.cboYouthRatioAttribute, self.dsbYouthRatioDefault)
        KeywordsDialogBase.setTabOrder(self.dsbYouthRatioDefault, self.cboAdultRatioAttribute)
        KeywordsDialogBase.setTabOrder(self.cboAdultRatioAttribute, self.dsbAdultRatioDefault)
        KeywordsDialogBase.setTabOrder(self.dsbAdultRatioDefault, self.cboElderlyRatioAttribute)
        KeywordsDialogBase.setTabOrder(self.cboElderlyRatioAttribute, self.dsbElderlyRatioDefault)
        KeywordsDialogBase.setTabOrder(self.dsbElderlyRatioDefault, self.pbnAdvanced)
        KeywordsDialogBase.setTabOrder(self.pbnAdvanced, self.radPredefined)
        KeywordsDialogBase.setTabOrder(self.radPredefined, self.radUserDefined)
        KeywordsDialogBase.setTabOrder(self.radUserDefined, self.cboKeyword)
        KeywordsDialogBase.setTabOrder(self.cboKeyword, self.lePredefinedValue)
        KeywordsDialogBase.setTabOrder(self.lePredefinedValue, self.pbnAddToList1)
        KeywordsDialogBase.setTabOrder(self.pbnAddToList1, self.leKey)
        KeywordsDialogBase.setTabOrder(self.leKey, self.leValue)
        KeywordsDialogBase.setTabOrder(self.leValue, self.pbnAddToList2)
        KeywordsDialogBase.setTabOrder(self.pbnAddToList2, self.lstKeywords)
        KeywordsDialogBase.setTabOrder(self.lstKeywords, self.pbnRemove)
        KeywordsDialogBase.setTabOrder(self.pbnRemove, self.buttonBox)
        KeywordsDialogBase.setTabOrder(self.buttonBox, self.scrollArea)

    def retranslateUi(self, KeywordsDialogBase):
        KeywordsDialogBase.setWindowTitle(_translate("KeywordsDialogBase", "InaSAFE - Keyword Editor", None))
        self.grpSimple.setTitle(_translate("KeywordsDialogBase", "Quick edit", None))
        self.lblAggregationAttribute.setText(_translate("KeywordsDialogBase", "Aggregation attribute", None))
        self.cboSubcategory.setToolTip(_translate("KeywordsDialogBase", "A subcategory represents the type of hazard.", None))
        self.lblFemaleRatioAttribute.setText(_translate("KeywordsDialogBase", "Female ratio attribute", None))
        self.lblSubcategory.setText(_translate("KeywordsDialogBase", "Subcategory", None))
        self.lblFemaleRatioDefault.setText(_translate("KeywordsDialogBase", "Female ratio default", None))
        self.lblSource.setText(_translate("KeywordsDialogBase", "&Source", None))
        self.radHazard.setToolTip(_translate("KeywordsDialogBase", "A hazard is a situation that poses a level of threat to life, health, property, or environment. (Wikipedia)", None))
        self.radHazard.setText(_translate("KeywordsDialogBase", "Hazard", None))
        self.radExposure.setToolTip(_translate("KeywordsDialogBase", "Where people and property are situated.", None))
        self.radExposure.setText(_translate("KeywordsDialogBase", "Exposure", None))
        self.radPostprocessing.setText(_translate("KeywordsDialogBase", "Postprocessing", None))
        self.lblTitle.setText(_translate("KeywordsDialogBase", "Title", None))
        self.lblCategory.setText(_translate("KeywordsDialogBase", "Category", None))
        self.lblElderlyRatioDefault.setText(_translate("KeywordsDialogBase", "Elderly ratio default", None))
        self.lblElderlyRatioAttribute.setText(_translate("KeywordsDialogBase", "Elderly ratio attribute", None))
        self.lblAdultRatioDefault.setText(_translate("KeywordsDialogBase", "Adult ratio default", None))
        self.lblAdultRatioAttribute.setText(_translate("KeywordsDialogBase", "Adult ratio attribute", None))
        self.lblYouthRatioDefault.setText(_translate("KeywordsDialogBase", "Youth ratio default", None))
        self.lblYouthRatioAttribute.setText(_translate("KeywordsDialogBase", "Youth ratio attribute", None))
        self.pbnAdvanced.setText(_translate("KeywordsDialogBase", "Show advanced editor", None))
        self.grpAdvanced.setTitle(_translate("KeywordsDialogBase", "Advanced editor", None))
        self.radPredefined.setText(_translate("KeywordsDialogBase", "Predefined", None))
        self.radUserDefined.setText(_translate("KeywordsDialogBase", "User defined", None))
        self.label_4.setText(_translate("KeywordsDialogBase", "Keyword", None))
        self.label_5.setText(_translate("KeywordsDialogBase", "Value", None))
        self.pbnAddToList1.setText(_translate("KeywordsDialogBase", "Add to list", None))
        self.label_6.setText(_translate("KeywordsDialogBase", "Key", None))
        self.label_7.setText(_translate("KeywordsDialogBase", "Value", None))
        self.pbnAddToList2.setText(_translate("KeywordsDialogBase", "Add to list", None))
        self.label_8.setText(_translate("KeywordsDialogBase", "Current keywords", None))
        self.pbnRemove.setText(_translate("KeywordsDialogBase", "Remove selected", None))

import resources_rc
