# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_dialog_base.ui'
#
# Created: Mon Feb 17 11:50:09 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OptionsDialogBase(object):
    def setupUi(self, OptionsDialogBase):
        OptionsDialogBase.setObjectName(_fromUtf8("OptionsDialogBase"))
        OptionsDialogBase.resize(683, 453)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OptionsDialogBase.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(OptionsDialogBase)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(OptionsDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(OptionsDialogBase)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_basic = QtGui.QWidget()
        self.tab_basic.setObjectName(_fromUtf8("tab_basic"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_basic)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.tab_basic)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 638, 454))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cbxVisibleLayersOnly = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbxVisibleLayersOnly.setObjectName(_fromUtf8("cbxVisibleLayersOnly"))
        self.gridLayout.addWidget(self.cbxVisibleLayersOnly, 0, 0, 1, 1)
        self.cbxSetLayerNameFromTitle = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbxSetLayerNameFromTitle.setEnabled(True)
        self.cbxSetLayerNameFromTitle.setObjectName(_fromUtf8("cbxSetLayerNameFromTitle"))
        self.gridLayout.addWidget(self.cbxSetLayerNameFromTitle, 1, 0, 1, 1)
        self.cbxZoomToImpact = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbxZoomToImpact.setEnabled(True)
        self.cbxZoomToImpact.setObjectName(_fromUtf8("cbxZoomToImpact"))
        self.gridLayout.addWidget(self.cbxZoomToImpact, 2, 0, 1, 1)
        self.cbxHideExposure = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbxHideExposure.setEnabled(True)
        self.cbxHideExposure.setObjectName(_fromUtf8("cbxHideExposure"))
        self.gridLayout.addWidget(self.cbxHideExposure, 3, 0, 1, 1)
        self.cbxClipToViewport = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbxClipToViewport.setChecked(False)
        self.cbxClipToViewport.setObjectName(_fromUtf8("cbxClipToViewport"))
        self.gridLayout.addWidget(self.cbxClipToViewport, 4, 0, 1, 1)
        self.cbxClipHard = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbxClipHard.setObjectName(_fromUtf8("cbxClipHard"))
        self.gridLayout.addWidget(self.cbxClipHard, 5, 0, 1, 1)
        self.cbxShowPostprocessingLayers = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbxShowPostprocessingLayers.setObjectName(_fromUtf8("cbxShowPostprocessingLayers"))
        self.gridLayout.addWidget(self.cbxShowPostprocessingLayers, 6, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.dsbFemaleRatioDefault = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.dsbFemaleRatioDefault.setAccelerated(True)
        self.dsbFemaleRatioDefault.setMaximum(1.0)
        self.dsbFemaleRatioDefault.setSingleStep(0.01)
        self.dsbFemaleRatioDefault.setObjectName(_fromUtf8("dsbFemaleRatioDefault"))
        self.horizontalLayout.addWidget(self.dsbFemaleRatioDefault)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 1)
        self.grpNotImplemented = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.grpNotImplemented.setObjectName(_fromUtf8("grpNotImplemented"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpNotImplemented)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEdit_4 = QtGui.QLineEdit(self.grpNotImplemented)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.toolButton_4 = QtGui.QToolButton(self.grpNotImplemented)
        self.toolButton_4.setEnabled(True)
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.horizontalLayout_4.addWidget(self.toolButton_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 8, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.grpNotImplemented)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 7, 0, 1, 1)
        self.cbxBubbleLayersUp = QtGui.QCheckBox(self.grpNotImplemented)
        self.cbxBubbleLayersUp.setEnabled(True)
        self.cbxBubbleLayersUp.setObjectName(_fromUtf8("cbxBubbleLayersUp"))
        self.gridLayout_3.addWidget(self.cbxBubbleLayersUp, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.grpNotImplemented)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox = QtGui.QSpinBox(self.grpNotImplemented)
        self.spinBox.setEnabled(True)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_5.addWidget(self.spinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 9, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit = QtGui.QLineEdit(self.grpNotImplemented)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.toolButton = QtGui.QToolButton(self.grpNotImplemented)
        self.toolButton.setEnabled(True)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.grpNotImplemented)
        self.label.setEnabled(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.cbxUseThread = QtGui.QCheckBox(self.grpNotImplemented)
        self.cbxUseThread.setObjectName(_fromUtf8("cbxUseThread"))
        self.gridLayout_3.addWidget(self.cbxUseThread, 10, 0, 1, 1)
        self.gridLayout.addWidget(self.grpNotImplemented, 8, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_basic, _fromUtf8(""))
        self.tab_templates = QtGui.QWidget()
        self.tab_templates.setObjectName(_fromUtf8("tab_templates"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_templates)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblOrganisationLogo = QtGui.QLabel(self.tab_templates)
        self.lblOrganisationLogo.setEnabled(True)
        self.lblOrganisationLogo.setObjectName(_fromUtf8("lblOrganisationLogo"))
        self.gridLayout_5.addWidget(self.lblOrganisationLogo, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.leOrgLogoPath = QtGui.QLineEdit(self.tab_templates)
        self.leOrgLogoPath.setEnabled(True)
        self.leOrgLogoPath.setObjectName(_fromUtf8("leOrgLogoPath"))
        self.horizontalLayout_9.addWidget(self.leOrgLogoPath)
        self.toolOrgLogoPath = QtGui.QToolButton(self.tab_templates)
        self.toolOrgLogoPath.setEnabled(True)
        self.toolOrgLogoPath.setObjectName(_fromUtf8("toolOrgLogoPath"))
        self.horizontalLayout_9.addWidget(self.toolOrgLogoPath)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.lblNorthArrowPath = QtGui.QLabel(self.tab_templates)
        self.lblNorthArrowPath.setEnabled(True)
        self.lblNorthArrowPath.setObjectName(_fromUtf8("lblNorthArrowPath"))
        self.gridLayout_5.addWidget(self.lblNorthArrowPath, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.leNorthArrowPath = QtGui.QLineEdit(self.tab_templates)
        self.leNorthArrowPath.setEnabled(True)
        self.leNorthArrowPath.setObjectName(_fromUtf8("leNorthArrowPath"))
        self.horizontalLayout_8.addWidget(self.leNorthArrowPath)
        self.toolNorthArrowPath = QtGui.QToolButton(self.tab_templates)
        self.toolNorthArrowPath.setEnabled(True)
        self.toolNorthArrowPath.setObjectName(_fromUtf8("toolNorthArrowPath"))
        self.horizontalLayout_8.addWidget(self.toolNorthArrowPath)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 3, 0, 1, 1)
        self.lblReportTemplate = QtGui.QLabel(self.tab_templates)
        self.lblReportTemplate.setEnabled(True)
        self.lblReportTemplate.setObjectName(_fromUtf8("lblReportTemplate"))
        self.gridLayout_5.addWidget(self.lblReportTemplate, 4, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.leReportTemplatePath = QtGui.QLineEdit(self.tab_templates)
        self.leReportTemplatePath.setEnabled(True)
        self.leReportTemplatePath.setObjectName(_fromUtf8("leReportTemplatePath"))
        self.horizontalLayout_10.addWidget(self.leReportTemplatePath)
        self.toolReportTemplatePath = QtGui.QToolButton(self.tab_templates)
        self.toolReportTemplatePath.setEnabled(True)
        self.toolReportTemplatePath.setObjectName(_fromUtf8("toolReportTemplatePath"))
        self.horizontalLayout_10.addWidget(self.toolReportTemplatePath)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_templates)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 6, 0, 1, 1)
        self.txtDisclaimer = QtGui.QPlainTextEdit(self.tab_templates)
        self.txtDisclaimer.setObjectName(_fromUtf8("txtDisclaimer"))
        self.gridLayout_5.addWidget(self.txtDisclaimer, 7, 0, 1, 1)
        self.tabWidget.addTab(self.tab_templates, _fromUtf8(""))
        self.tab_advanced = QtGui.QWidget()
        self.tab_advanced.setObjectName(_fromUtf8("tab_advanced"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_advanced)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblKeywordCache = QtGui.QLabel(self.tab_advanced)
        self.lblKeywordCache.setEnabled(True)
        self.lblKeywordCache.setObjectName(_fromUtf8("lblKeywordCache"))
        self.gridLayout_6.addWidget(self.lblKeywordCache, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.leKeywordCachePath = QtGui.QLineEdit(self.tab_advanced)
        self.leKeywordCachePath.setEnabled(True)
        self.leKeywordCachePath.setObjectName(_fromUtf8("leKeywordCachePath"))
        self.horizontalLayout_6.addWidget(self.leKeywordCachePath)
        self.toolKeywordCachePath = QtGui.QToolButton(self.tab_advanced)
        self.toolKeywordCachePath.setEnabled(True)
        self.toolKeywordCachePath.setObjectName(_fromUtf8("toolKeywordCachePath"))
        self.horizontalLayout_6.addWidget(self.toolKeywordCachePath)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.cbxUseSentry = QtGui.QCheckBox(self.tab_advanced)
        self.cbxUseSentry.setObjectName(_fromUtf8("cbxUseSentry"))
        self.gridLayout_6.addWidget(self.cbxUseSentry, 2, 0, 1, 1)
        self.textBrowser = QtGui.QTextBrowser(self.tab_advanced)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_6.addWidget(self.textBrowser, 3, 0, 1, 1)
        self.cbxDevMode = QtGui.QCheckBox(self.tab_advanced)
        self.cbxDevMode.setObjectName(_fromUtf8("cbxDevMode"))
        self.gridLayout_6.addWidget(self.cbxDevMode, 4, 0, 1, 1)
        self.cbxNativeZonalStats = QtGui.QCheckBox(self.tab_advanced)
        self.cbxNativeZonalStats.setObjectName(_fromUtf8("cbxNativeZonalStats"))
        self.gridLayout_6.addWidget(self.cbxNativeZonalStats, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab_advanced, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(OptionsDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), OptionsDialogBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), OptionsDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialogBase)
        OptionsDialogBase.setTabOrder(self.cbxVisibleLayersOnly, self.lineEdit)
        OptionsDialogBase.setTabOrder(self.lineEdit, self.cbxSetLayerNameFromTitle)
        OptionsDialogBase.setTabOrder(self.cbxSetLayerNameFromTitle, self.lineEdit_4)
        OptionsDialogBase.setTabOrder(self.lineEdit_4, self.toolButton_4)
        OptionsDialogBase.setTabOrder(self.toolButton_4, self.spinBox)
        OptionsDialogBase.setTabOrder(self.spinBox, self.tabWidget)
        OptionsDialogBase.setTabOrder(self.tabWidget, self.cbxZoomToImpact)
        OptionsDialogBase.setTabOrder(self.cbxZoomToImpact, self.cbxHideExposure)
        OptionsDialogBase.setTabOrder(self.cbxHideExposure, self.cbxBubbleLayersUp)
        OptionsDialogBase.setTabOrder(self.cbxBubbleLayersUp, self.toolButton)
        OptionsDialogBase.setTabOrder(self.toolButton, self.cbxShowPostprocessingLayers)
        OptionsDialogBase.setTabOrder(self.cbxShowPostprocessingLayers, self.buttonBox)
        OptionsDialogBase.setTabOrder(self.buttonBox, self.cbxClipToViewport)
        OptionsDialogBase.setTabOrder(self.cbxClipToViewport, self.cbxUseThread)
        OptionsDialogBase.setTabOrder(self.cbxUseThread, self.dsbFemaleRatioDefault)
        OptionsDialogBase.setTabOrder(self.dsbFemaleRatioDefault, self.cbxClipHard)
        OptionsDialogBase.setTabOrder(self.cbxClipHard, self.scrollArea)
        OptionsDialogBase.setTabOrder(self.scrollArea, self.txtDisclaimer)
        OptionsDialogBase.setTabOrder(self.txtDisclaimer, self.leNorthArrowPath)
        OptionsDialogBase.setTabOrder(self.leNorthArrowPath, self.toolNorthArrowPath)
        OptionsDialogBase.setTabOrder(self.toolNorthArrowPath, self.leOrgLogoPath)
        OptionsDialogBase.setTabOrder(self.leOrgLogoPath, self.toolOrgLogoPath)
        OptionsDialogBase.setTabOrder(self.toolOrgLogoPath, self.cbxDevMode)
        OptionsDialogBase.setTabOrder(self.cbxDevMode, self.textBrowser)
        OptionsDialogBase.setTabOrder(self.textBrowser, self.cbxUseSentry)
        OptionsDialogBase.setTabOrder(self.cbxUseSentry, self.leKeywordCachePath)
        OptionsDialogBase.setTabOrder(self.leKeywordCachePath, self.toolKeywordCachePath)

    def retranslateUi(self, OptionsDialogBase):
        OptionsDialogBase.setWindowTitle(_translate("OptionsDialogBase", "InaSAFE - Options", None))
        self.cbxVisibleLayersOnly.setText(_translate("OptionsDialogBase", "Only show visible layers in InaSAFE dock", None))
        self.cbxSetLayerNameFromTitle.setText(_translate("OptionsDialogBase", "Set QGIS layer name from \'title\' in keywords", None))
        self.cbxZoomToImpact.setText(_translate("OptionsDialogBase", "Zoom to impact layer on scenario estimate completion", None))
        self.cbxHideExposure.setText(_translate("OptionsDialogBase", "Hide exposure layer on scenario estimate completion", None))
        self.cbxClipToViewport.setToolTip(_translate("OptionsDialogBase", "Turn on to clip hazard and exposure layers to the currently  visible extent on the map canvas", None))
        self.cbxClipToViewport.setText(_translate("OptionsDialogBase", "Clip datasets to visible extent before analysis", None))
        self.cbxClipHard.setText(_translate("OptionsDialogBase", "When clipping, also clip features (i.e. will clip polygon smaller)", None))
        self.cbxShowPostprocessingLayers.setToolTip(_translate("OptionsDialogBase", "Turn on to see the intermediate files generated by the postprocessing steps in the map canvas", None))
        self.cbxShowPostprocessingLayers.setText(_translate("OptionsDialogBase", "Show intermediate layers generated by postprocessing", None))
        self.label_6.setText(_translate("OptionsDialogBase", "Female ratio default value", None))
        self.grpNotImplemented.setTitle(_translate("OptionsDialogBase", "Not yet implemented", None))
        self.toolButton_4.setText(_translate("OptionsDialogBase", "...", None))
        self.label_4.setText(_translate("OptionsDialogBase", "Organisation name (for maps, reports etc.)", None))
        self.cbxBubbleLayersUp.setText(_translate("OptionsDialogBase", "Bubble exposure and hazard layers to top when selected", None))
        self.label_5.setText(_translate("OptionsDialogBase", "DPI (Maps and reports)", None))
        self.toolButton.setText(_translate("OptionsDialogBase", "...", None))
        self.label.setText(_translate("OptionsDialogBase", "Location for results", None))
        self.cbxUseThread.setText(_translate("OptionsDialogBase", "Run analysis in a separate thread (experimental)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_basic), _translate("OptionsDialogBase", "Basic Options", None))
        self.lblOrganisationLogo.setText(_translate("OptionsDialogBase", "Organisation logo", None))
        self.toolOrgLogoPath.setText(_translate("OptionsDialogBase", "...", None))
        self.lblNorthArrowPath.setText(_translate("OptionsDialogBase", "North arrow image", None))
        self.toolNorthArrowPath.setText(_translate("OptionsDialogBase", "...", None))
        self.lblReportTemplate.setText(_translate("OptionsDialogBase", "Report templates directory", None))
        self.toolReportTemplatePath.setText(_translate("OptionsDialogBase", "...", None))
        self.label_2.setText(_translate("OptionsDialogBase", "Organisation disclaimer text", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_templates), _translate("OptionsDialogBase", "Template Options", None))
        self.lblKeywordCache.setText(_translate("OptionsDialogBase", "Keyword cache for remote datasources", None))
        self.toolKeywordCachePath.setText(_translate("OptionsDialogBase", "...", None))
        self.cbxUseSentry.setText(_translate("OptionsDialogBase", "Help to improve InaSAFE by submitting errors to a remote server", None))
        self.textBrowser.setHtml(_translate("OptionsDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Lucida Grande UI\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:12pt; font-weight:600; color:#f50000;\">Note:</span><span style=\" font-family:\'Cantarell\'; font-size:12pt;\"> The above setting requires a QGIS restart to disable / enable. Error messages and diagnostic information will be posted to http://sentry.linfiniti.com/inasafe-desktop/. Some institutions may not allow you to enable this feature - check with your network administrator if unsure. Although the data is submitted anonymously, the information contained in tracebacks may contain file system paths which reveal your identity or other information from your system.</span></p></body></html>", None))
        self.cbxDevMode.setText(_translate("OptionsDialogBase", "Enable developer mode for dock webkit (needs restart)", None))
        self.cbxNativeZonalStats.setText(_translate("OptionsDialogBase", "Use QGIS zonal statistics (leave unchecked to use InaSAFE\'s zonal statistics)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_advanced), _translate("OptionsDialogBase", "Advanced", None))

import resources_rc
