# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard_dialog_base.ui'
#
# Created: Sun Oct 26 23:02:00 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardDialogBase(object):
    def setupUi(self, WizardDialogBase):
        WizardDialogBase.setObjectName(_fromUtf8("WizardDialogBase"))
        WizardDialogBase.resize(1017, 532)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WizardDialogBase.sizePolicy().hasHeightForWidth())
        WizardDialogBase.setSizePolicy(sizePolicy)
        WizardDialogBase.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WizardDialogBase.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(WizardDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.lblMainTitle = QtGui.QLabel(WizardDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMainTitle.sizePolicy().hasHeightForWidth())
        self.lblMainTitle.setSizePolicy(sizePolicy)
        self.lblMainTitle.setStyleSheet(_fromUtf8("font: 14pt;"))
        self.lblMainTitle.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lblMainTitle.setObjectName(_fromUtf8("lblMainTitle"))
        self.gridLayout_12.addWidget(self.lblMainTitle, 0, 1, 1, 1)
        self.lblSubtitle = QtGui.QLabel(WizardDialogBase)
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lblSubtitle.setIndent(-1)
        self.lblSubtitle.setObjectName(_fromUtf8("lblSubtitle"))
        self.gridLayout_12.addWidget(self.lblSubtitle, 1, 1, 1, 1)
        self.lblMainIcon = QtGui.QLabel(WizardDialogBase)
        self.lblMainIcon.setMaximumSize(QtCore.QSize(40, 60))
        self.lblMainIcon.setText(_fromUtf8(""))
        self.lblMainIcon.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.svg")))
        self.lblMainIcon.setScaledContents(False)
        self.lblMainIcon.setObjectName(_fromUtf8("lblMainIcon"))
        self.gridLayout_12.addWidget(self.lblMainIcon, 0, 0, 2, 1)
        self.lblStep = QtGui.QLabel(WizardDialogBase)
        self.lblStep.setStyleSheet(_fromUtf8("font: 14pt;"))
        self.lblStep.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblStep.setObjectName(_fromUtf8("lblStep"))
        self.gridLayout_12.addWidget(self.lblStep, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_12)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtGui.QFrame(WizardDialogBase)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.stackedWidget = QtGui.QStackedWidget(WizardDialogBase)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet(_fromUtf8("font-size:10pt"))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pg1Category = QtGui.QWidget()
        self.pg1Category.setStyleSheet(_fromUtf8(""))
        self.pg1Category.setObjectName(_fromUtf8("pg1Category"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pg1Category)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblSelectCategory = QtGui.QLabel(self.pg1Category)
        self.lblSelectCategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectCategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectCategory.setWordWrap(True)
        self.lblSelectCategory.setObjectName(_fromUtf8("lblSelectCategory"))
        self.verticalLayout_2.addWidget(self.lblSelectCategory)
        spacerItem2 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 0, 4, 1)
        self.lstCategories = QtGui.QListWidget(self.pg1Category)
        self.lstCategories.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstCategories.sizePolicy().hasHeightForWidth())
        self.lstCategories.setSizePolicy(sizePolicy)
        self.lstCategories.setMinimumSize(QtCore.QSize(220, 100))
        self.lstCategories.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstCategories.setObjectName(_fromUtf8("lstCategories"))
        self.gridLayout_6.addWidget(self.lstCategories, 0, 1, 4, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 2, 4, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 5, 4, 1)
        self.lblDescribeCategory = QtGui.QLabel(self.pg1Category)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeCategory.sizePolicy().hasHeightForWidth())
        self.lblDescribeCategory.setSizePolicy(sizePolicy)
        self.lblDescribeCategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDescribeCategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDescribeCategory.setWordWrap(True)
        self.lblDescribeCategory.setObjectName(_fromUtf8("lblDescribeCategory"))
        self.gridLayout_6.addWidget(self.lblDescribeCategory, 3, 3, 1, 1)
        self.lblIconCategory = QtGui.QLabel(self.pg1Category)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIconCategory.sizePolicy().hasHeightForWidth())
        self.lblIconCategory.setSizePolicy(sizePolicy)
        self.lblIconCategory.setMinimumSize(QtCore.QSize(192, 192))
        self.lblIconCategory.setMaximumSize(QtCore.QSize(192, 192))
        self.lblIconCategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblIconCategory.setScaledContents(True)
        self.lblIconCategory.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIconCategory.setObjectName(_fromUtf8("lblIconCategory"))
        self.gridLayout_6.addWidget(self.lblIconCategory, 2, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        spacerItem6 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.stackedWidget.addWidget(self.pg1Category)
        self.pg2Subcategory = QtGui.QWidget()
        self.pg2Subcategory.setStyleSheet(_fromUtf8(""))
        self.pg2Subcategory.setObjectName(_fromUtf8("pg2Subcategory"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pg2Subcategory)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblSelectSubcategory = QtGui.QLabel(self.pg2Subcategory)
        self.lblSelectSubcategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectSubcategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectSubcategory.setWordWrap(True)
        self.lblSelectSubcategory.setObjectName(_fromUtf8("lblSelectSubcategory"))
        self.verticalLayout_3.addWidget(self.lblSelectSubcategory)
        spacerItem7 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 2, 3, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 0, 3, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 5, 3, 1)
        self.lblDescribeSubcategory = QtGui.QLabel(self.pg2Subcategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeSubcategory.sizePolicy().hasHeightForWidth())
        self.lblDescribeSubcategory.setSizePolicy(sizePolicy)
        self.lblDescribeSubcategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDescribeSubcategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDescribeSubcategory.setWordWrap(True)
        self.lblDescribeSubcategory.setMargin(0)
        self.lblDescribeSubcategory.setObjectName(_fromUtf8("lblDescribeSubcategory"))
        self.gridLayout.addWidget(self.lblDescribeSubcategory, 2, 3, 1, 1)
        self.lblIconSubcategory = QtGui.QLabel(self.pg2Subcategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIconSubcategory.sizePolicy().hasHeightForWidth())
        self.lblIconSubcategory.setSizePolicy(sizePolicy)
        self.lblIconSubcategory.setMinimumSize(QtCore.QSize(192, 192))
        self.lblIconSubcategory.setMaximumSize(QtCore.QSize(192, 192))
        self.lblIconSubcategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblIconSubcategory.setScaledContents(True)
        self.lblIconSubcategory.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIconSubcategory.setWordWrap(True)
        self.lblIconSubcategory.setObjectName(_fromUtf8("lblIconSubcategory"))
        self.gridLayout.addWidget(self.lblIconSubcategory, 1, 3, 1, 1)
        self.lstSubcategories = QtGui.QListWidget(self.pg2Subcategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstSubcategories.sizePolicy().hasHeightForWidth())
        self.lstSubcategories.setSizePolicy(sizePolicy)
        self.lstSubcategories.setMinimumSize(QtCore.QSize(220, 0))
        self.lstSubcategories.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstSubcategories.setBaseSize(QtCore.QSize(0, 0))
        self.lstSubcategories.setObjectName(_fromUtf8("lstSubcategories"))
        self.gridLayout.addWidget(self.lstSubcategories, 0, 1, 3, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem11 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem11)
        self.stackedWidget.addWidget(self.pg2Subcategory)
        self.pg3Units = QtGui.QWidget()
        self.pg3Units.setObjectName(_fromUtf8("pg3Units"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pg3Units)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblSelectUnit = QtGui.QLabel(self.pg3Units)
        self.lblSelectUnit.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectUnit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectUnit.setWordWrap(True)
        self.lblSelectUnit.setObjectName(_fromUtf8("lblSelectUnit"))
        self.verticalLayout_4.addWidget(self.lblSelectUnit)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem12)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem13 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 0, 0, 1, 1)
        self.lstUnits = QtGui.QListWidget(self.pg3Units)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstUnits.sizePolicy().hasHeightForWidth())
        self.lstUnits.setSizePolicy(sizePolicy)
        self.lstUnits.setMinimumSize(QtCore.QSize(220, 0))
        self.lstUnits.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstUnits.setBaseSize(QtCore.QSize(0, 0))
        self.lstUnits.setObjectName(_fromUtf8("lstUnits"))
        self.gridLayout_2.addWidget(self.lstUnits, 0, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 0, 2, 1, 1)
        self.lblDescribeUnit = QtGui.QLabel(self.pg3Units)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeUnit.sizePolicy().hasHeightForWidth())
        self.lblDescribeUnit.setSizePolicy(sizePolicy)
        self.lblDescribeUnit.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDescribeUnit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDescribeUnit.setWordWrap(True)
        self.lblDescribeUnit.setMargin(0)
        self.lblDescribeUnit.setObjectName(_fromUtf8("lblDescribeUnit"))
        self.gridLayout_2.addWidget(self.lblDescribeUnit, 0, 3, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 0, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        spacerItem16 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem16)
        self.stackedWidget.addWidget(self.pg3Units)
        self.pg4Field = QtGui.QWidget()
        self.pg4Field.setObjectName(_fromUtf8("pg4Field"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pg4Field)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lblSelectField = QtGui.QLabel(self.pg4Field)
        self.lblSelectField.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectField.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectField.setWordWrap(True)
        self.lblSelectField.setObjectName(_fromUtf8("lblSelectField"))
        self.verticalLayout_5.addWidget(self.lblSelectField)
        spacerItem17 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem17)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem18 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 1, 5, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 1, 0, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 1, 3, 1, 1)
        self.lstFields = QtGui.QListWidget(self.pg4Field)
        self.lstFields.setObjectName(_fromUtf8("lstFields"))
        self.gridLayout_3.addWidget(self.lstFields, 1, 1, 1, 2)
        self.lblDescribeField = QtGui.QLabel(self.pg4Field)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeField.sizePolicy().hasHeightForWidth())
        self.lblDescribeField.setSizePolicy(sizePolicy)
        self.lblDescribeField.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDescribeField.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblDescribeField.setWordWrap(True)
        self.lblDescribeField.setObjectName(_fromUtf8("lblDescribeField"))
        self.gridLayout_3.addWidget(self.lblDescribeField, 1, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        spacerItem21 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem21)
        self.stackedWidget.addWidget(self.pg4Field)
        self.pg5Categories = QtGui.QWidget()
        self.pg5Categories.setObjectName(_fromUtf8("pg5Categories"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.pg5Categories)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.lblClassify = QtGui.QLabel(self.pg5Categories)
        self.lblClassify.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblClassify.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblClassify.setWordWrap(True)
        self.lblClassify.setObjectName(_fromUtf8("lblClassify"))
        self.verticalLayout_14.addWidget(self.lblClassify)
        spacerItem22 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem22)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.treeClasses = QtGui.QTreeWidget(self.pg5Categories)
        self.treeClasses.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.treeClasses.setProperty("showDropIndicator", True)
        self.treeClasses.setDragEnabled(False)
        self.treeClasses.setDragDropOverwriteMode(False)
        self.treeClasses.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.treeClasses.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeClasses.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.treeClasses.setRootIsDecorated(False)
        self.treeClasses.setItemsExpandable(False)
        self.treeClasses.setExpandsOnDoubleClick(False)
        self.treeClasses.setObjectName(_fromUtf8("treeClasses"))
        self.treeClasses.header().setVisible(False)
        self.gridLayout_15.addWidget(self.treeClasses, 1, 5, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem23, 1, 4, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem24, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.pg5Categories)
        self.label_8.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_15.addWidget(self.label_8, 0, 5, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem25, 1, 2, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem26, 1, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.pg5Categories)
        self.label_7.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_15.addWidget(self.label_7, 0, 1, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem27, 1, 3, 1, 1)
        self.lstUniqueValues = QtGui.QListWidget(self.pg5Categories)
        self.lstUniqueValues.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lstUniqueValues.setDragEnabled(False)
        self.lstUniqueValues.setDragDropOverwriteMode(False)
        self.lstUniqueValues.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.lstUniqueValues.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lstUniqueValues.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lstUniqueValues.setObjectName(_fromUtf8("lstUniqueValues"))
        self.gridLayout_15.addWidget(self.lstUniqueValues, 1, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_15)
        spacerItem28 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_14.addItem(spacerItem28)
        self.stackedWidget.addWidget(self.pg5Categories)
        self.pg6Aggregations = QtGui.QWidget()
        self.pg6Aggregations.setEnabled(True)
        self.pg6Aggregations.setObjectName(_fromUtf8("pg6Aggregations"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.pg6Aggregations)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lblAggregation = QtGui.QLabel(self.pg6Aggregations)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblAggregation.setFont(font)
        self.lblAggregation.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblAggregation.setObjectName(_fromUtf8("lblAggregation"))
        self.verticalLayout_8.addWidget(self.lblAggregation)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblYouthRatioAttribute = QtGui.QLabel(self.pg6Aggregations)
        self.lblYouthRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblYouthRatioAttribute.setObjectName(_fromUtf8("lblYouthRatioAttribute"))
        self.gridLayout_7.addWidget(self.lblYouthRatioAttribute, 2, 0, 1, 1)
        self.dsbFemaleRatioDefault = QtGui.QDoubleSpinBox(self.pg6Aggregations)
        self.dsbFemaleRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.dsbFemaleRatioDefault.setMaximum(1.0)
        self.dsbFemaleRatioDefault.setSingleStep(0.01)
        self.dsbFemaleRatioDefault.setObjectName(_fromUtf8("dsbFemaleRatioDefault"))
        self.gridLayout_7.addWidget(self.dsbFemaleRatioDefault, 1, 1, 1, 1)
        self.cboYouthRatioAttribute = QtGui.QComboBox(self.pg6Aggregations)
        self.cboYouthRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.cboYouthRatioAttribute.setObjectName(_fromUtf8("cboYouthRatioAttribute"))
        self.gridLayout_7.addWidget(self.cboYouthRatioAttribute, 2, 1, 1, 1)
        self.lblAdultRatioAttribute = QtGui.QLabel(self.pg6Aggregations)
        self.lblAdultRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblAdultRatioAttribute.setObjectName(_fromUtf8("lblAdultRatioAttribute"))
        self.gridLayout_7.addWidget(self.lblAdultRatioAttribute, 4, 0, 1, 1)
        self.dsbAdultRatioDefault = QtGui.QDoubleSpinBox(self.pg6Aggregations)
        self.dsbAdultRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.dsbAdultRatioDefault.setMaximum(1.0)
        self.dsbAdultRatioDefault.setSingleStep(0.01)
        self.dsbAdultRatioDefault.setObjectName(_fromUtf8("dsbAdultRatioDefault"))
        self.gridLayout_7.addWidget(self.dsbAdultRatioDefault, 5, 1, 1, 1)
        self.cboElderlyRatioAttribute = QtGui.QComboBox(self.pg6Aggregations)
        self.cboElderlyRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.cboElderlyRatioAttribute.setObjectName(_fromUtf8("cboElderlyRatioAttribute"))
        self.gridLayout_7.addWidget(self.cboElderlyRatioAttribute, 6, 1, 1, 1)
        self.cboFemaleRatioAttribute = QtGui.QComboBox(self.pg6Aggregations)
        self.cboFemaleRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.cboFemaleRatioAttribute.setObjectName(_fromUtf8("cboFemaleRatioAttribute"))
        self.gridLayout_7.addWidget(self.cboFemaleRatioAttribute, 0, 1, 1, 1)
        self.lblFemaleRatioDefault = QtGui.QLabel(self.pg6Aggregations)
        self.lblFemaleRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblFemaleRatioDefault.setObjectName(_fromUtf8("lblFemaleRatioDefault"))
        self.gridLayout_7.addWidget(self.lblFemaleRatioDefault, 1, 0, 1, 1)
        self.lblAdultRatioDefault = QtGui.QLabel(self.pg6Aggregations)
        self.lblAdultRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblAdultRatioDefault.setObjectName(_fromUtf8("lblAdultRatioDefault"))
        self.gridLayout_7.addWidget(self.lblAdultRatioDefault, 5, 0, 1, 1)
        self.lblElderlyRatioAttribute = QtGui.QLabel(self.pg6Aggregations)
        self.lblElderlyRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblElderlyRatioAttribute.setObjectName(_fromUtf8("lblElderlyRatioAttribute"))
        self.gridLayout_7.addWidget(self.lblElderlyRatioAttribute, 6, 0, 1, 1)
        self.cboAdultRatioAttribute = QtGui.QComboBox(self.pg6Aggregations)
        self.cboAdultRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.cboAdultRatioAttribute.setObjectName(_fromUtf8("cboAdultRatioAttribute"))
        self.gridLayout_7.addWidget(self.cboAdultRatioAttribute, 4, 1, 1, 1)
        self.dsbYouthRatioDefault = QtGui.QDoubleSpinBox(self.pg6Aggregations)
        self.dsbYouthRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.dsbYouthRatioDefault.setMaximum(1.0)
        self.dsbYouthRatioDefault.setSingleStep(0.01)
        self.dsbYouthRatioDefault.setObjectName(_fromUtf8("dsbYouthRatioDefault"))
        self.gridLayout_7.addWidget(self.dsbYouthRatioDefault, 3, 1, 1, 1)
        self.lblFemaleRatioAttribute = QtGui.QLabel(self.pg6Aggregations)
        self.lblFemaleRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblFemaleRatioAttribute.setObjectName(_fromUtf8("lblFemaleRatioAttribute"))
        self.gridLayout_7.addWidget(self.lblFemaleRatioAttribute, 0, 0, 1, 1)
        self.lblElderlyRatioDefault = QtGui.QLabel(self.pg6Aggregations)
        self.lblElderlyRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblElderlyRatioDefault.setObjectName(_fromUtf8("lblElderlyRatioDefault"))
        self.gridLayout_7.addWidget(self.lblElderlyRatioDefault, 7, 0, 1, 1)
        self.dsbElderlyRatioDefault = QtGui.QDoubleSpinBox(self.pg6Aggregations)
        self.dsbElderlyRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.dsbElderlyRatioDefault.setMaximum(1.0)
        self.dsbElderlyRatioDefault.setSingleStep(0.01)
        self.dsbElderlyRatioDefault.setObjectName(_fromUtf8("dsbElderlyRatioDefault"))
        self.gridLayout_7.addWidget(self.dsbElderlyRatioDefault, 7, 1, 1, 1)
        self.lblYouthRatioDefault = QtGui.QLabel(self.pg6Aggregations)
        self.lblYouthRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblYouthRatioDefault.setObjectName(_fromUtf8("lblYouthRatioDefault"))
        self.gridLayout_7.addWidget(self.lblYouthRatioDefault, 3, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem29)
        self.stackedWidget.addWidget(self.pg6Aggregations)
        self.pg7Source = QtGui.QWidget()
        self.pg7Source.setObjectName(_fromUtf8("pg7Source"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pg7Source)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lblSelectSource = QtGui.QLabel(self.pg7Source)
        self.lblSelectSource.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectSource.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectSource.setWordWrap(True)
        self.lblSelectSource.setObjectName(_fromUtf8("lblSelectSource"))
        self.verticalLayout_6.addWidget(self.lblSelectSource)
        spacerItem30 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem30)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblScale = QtGui.QLabel(self.pg7Source)
        self.lblScale.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblScale.setObjectName(_fromUtf8("lblScale"))
        self.gridLayout_4.addWidget(self.lblScale, 4, 1, 1, 1)
        self.lblDate = QtGui.QLabel(self.pg7Source)
        self.lblDate.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout_4.addWidget(self.lblDate, 6, 1, 1, 1)
        self.leSource_url = QtGui.QLineEdit(self.pg7Source)
        self.leSource_url.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leSource_url.setObjectName(_fromUtf8("leSource_url"))
        self.gridLayout_4.addWidget(self.leSource_url, 2, 2, 1, 1)
        self.leSource_date = QtGui.QLineEdit(self.pg7Source)
        self.leSource_date.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leSource_date.setObjectName(_fromUtf8("leSource_date"))
        self.gridLayout_4.addWidget(self.leSource_date, 6, 2, 1, 1)
        spacerItem31 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem31, 3, 2, 1, 1)
        self.leSource_scale = QtGui.QLineEdit(self.pg7Source)
        self.leSource_scale.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leSource_scale.setObjectName(_fromUtf8("leSource_scale"))
        self.gridLayout_4.addWidget(self.leSource_scale, 4, 2, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem32, 0, 0, 1, 1)
        self.lblSource = QtGui.QLabel(self.pg7Source)
        self.lblSource.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSource.setObjectName(_fromUtf8("lblSource"))
        self.gridLayout_4.addWidget(self.lblSource, 0, 1, 1, 1)
        self.leSource = QtGui.QLineEdit(self.pg7Source)
        self.leSource.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leSource.setObjectName(_fromUtf8("leSource"))
        self.gridLayout_4.addWidget(self.leSource, 0, 2, 1, 1)
        spacerItem33 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem33, 0, 3, 1, 1)
        self.lblURL = QtGui.QLabel(self.pg7Source)
        self.lblURL.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblURL.setObjectName(_fromUtf8("lblURL"))
        self.gridLayout_4.addWidget(self.lblURL, 2, 1, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem34, 1, 2, 1, 1)
        spacerItem35 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem35, 5, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        spacerItem36 = QtGui.QSpacerItem(20, 166, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem36)
        self.stackedWidget.addWidget(self.pg7Source)
        self.pg8Title = QtGui.QWidget()
        self.pg8Title.setObjectName(_fromUtf8("pg8Title"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.pg8Title)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lblSelectTitle = QtGui.QLabel(self.pg8Title)
        self.lblSelectTitle.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectTitle.setWordWrap(True)
        self.lblSelectTitle.setObjectName(_fromUtf8("lblSelectTitle"))
        self.verticalLayout_7.addWidget(self.lblSelectTitle)
        spacerItem37 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem37)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem38 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem38, 0, 0, 1, 1)
        self.lblTitle = QtGui.QLabel(self.pg8Title)
        self.lblTitle.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gridLayout_5.addWidget(self.lblTitle, 0, 1, 1, 1)
        self.leTitle = QtGui.QLineEdit(self.pg8Title)
        self.leTitle.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leTitle.setObjectName(_fromUtf8("leTitle"))
        self.gridLayout_5.addWidget(self.leTitle, 0, 2, 1, 1)
        spacerItem39 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem39, 0, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        spacerItem40 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem40)
        self.stackedWidget.addWidget(self.pg8Title)
        self.pgF1Function = QtGui.QWidget()
        self.pgF1Function.setObjectName(_fromUtf8("pgF1Function"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.pgF1Function)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lblSelectFunction = QtGui.QLabel(self.pgF1Function)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSelectFunction.sizePolicy().hasHeightForWidth())
        self.lblSelectFunction.setSizePolicy(sizePolicy)
        self.lblSelectFunction.setBaseSize(QtCore.QSize(0, 0))
        self.lblSelectFunction.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectFunction.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectFunction.setWordWrap(True)
        self.lblSelectFunction.setObjectName(_fromUtf8("lblSelectFunction"))
        self.verticalLayout_9.addWidget(self.lblSelectFunction)
        spacerItem41 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem41)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem42 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem42, 0, 0, 1, 1)
        self.treeFunctions = QtGui.QTreeWidget(self.pgF1Function)
        self.treeFunctions.setMinimumSize(QtCore.QSize(360, 99))
        self.treeFunctions.setMaximumSize(QtCore.QSize(360, 16777215))
        self.treeFunctions.setObjectName(_fromUtf8("treeFunctions"))
        self.treeFunctions.headerItem().setText(0, _fromUtf8("1"))
        self.treeFunctions.header().setVisible(False)
        self.gridLayout_8.addWidget(self.treeFunctions, 0, 1, 1, 1)
        spacerItem43 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem43, 0, 2, 1, 1)
        self.lblDescribeFunction = QtGui.QLabel(self.pgF1Function)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeFunction.sizePolicy().hasHeightForWidth())
        self.lblDescribeFunction.setSizePolicy(sizePolicy)
        self.lblDescribeFunction.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lblDescribeFunction.setWordWrap(True)
        self.lblDescribeFunction.setObjectName(_fromUtf8("lblDescribeFunction"))
        self.gridLayout_8.addWidget(self.lblDescribeFunction, 0, 3, 1, 1)
        spacerItem44 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem44, 0, 4, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_8)
        spacerItem45 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem45)
        self.stackedWidget.addWidget(self.pgF1Function)
        self.pgF2Origin = QtGui.QWidget()
        self.pgF2Origin.setObjectName(_fromUtf8("pgF2Origin"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.pgF2Origin)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        spacerItem46 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem46)
        self.lblSelectLayerOriginType = QtGui.QLabel(self.pgF2Origin)
        self.lblSelectLayerOriginType.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectLayerOriginType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectLayerOriginType.setWordWrap(True)
        self.lblSelectLayerOriginType.setObjectName(_fromUtf8("lblSelectLayerOriginType"))
        self.verticalLayout_11.addWidget(self.lblSelectLayerOriginType)
        spacerItem47 = QtGui.QSpacerItem(20, 36, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem47)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.rbLayerFromCanvas = QtGui.QRadioButton(self.pgF2Origin)
        self.rbLayerFromCanvas.setObjectName(_fromUtf8("rbLayerFromCanvas"))
        self.gridLayout_13.addWidget(self.rbLayerFromCanvas, 4, 1, 1, 1)
        spacerItem48 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem48, 2, 3, 6, 1)
        spacerItem49 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem49, 2, 0, 6, 1)
        self.rbLayerFromDisk = QtGui.QRadioButton(self.pgF2Origin)
        self.rbLayerFromDisk.setObjectName(_fromUtf8("rbLayerFromDisk"))
        self.gridLayout_13.addWidget(self.rbLayerFromDisk, 5, 1, 1, 1)
        self.rbNoAggregation = QtGui.QRadioButton(self.pgF2Origin)
        self.rbNoAggregation.setObjectName(_fromUtf8("rbNoAggregation"))
        self.gridLayout_13.addWidget(self.rbNoAggregation, 7, 1, 1, 1)
        spacerItem50 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem50, 6, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_13)
        spacerItem51 = QtGui.QSpacerItem(20, 109, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem51)
        self.stackedWidget.addWidget(self.pgF2Origin)
        self.pgF3aLayerTOC = QtGui.QWidget()
        self.pgF3aLayerTOC.setObjectName(_fromUtf8("pgF3aLayerTOC"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.pgF3aLayerTOC)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lblSelectHazardLayer = QtGui.QLabel(self.pgF3aLayerTOC)
        self.lblSelectHazardLayer.setStyleSheet(_fromUtf8(""))
        self.lblSelectHazardLayer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectHazardLayer.setWordWrap(True)
        self.lblSelectHazardLayer.setObjectName(_fromUtf8("lblSelectHazardLayer"))
        self.verticalLayout_10.addWidget(self.lblSelectHazardLayer)
        spacerItem52 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem52)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        spacerItem53 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem53, 0, 2, 1, 1)
        self.lblDescribeHazardLayer_2 = QtGui.QLabel(self.pgF3aLayerTOC)
        self.lblDescribeHazardLayer_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblDescribeHazardLayer_2.setObjectName(_fromUtf8("lblDescribeHazardLayer_2"))
        self.gridLayout_16.addWidget(self.lblDescribeHazardLayer_2, 0, 3, 1, 1)
        spacerItem54 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem54, 0, 4, 1, 1)
        spacerItem55 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem55, 0, 0, 1, 1)
        self.lstHazardLayers_2 = QtGui.QListWidget(self.pgF3aLayerTOC)
        self.lstHazardLayers_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstHazardLayers_2.sizePolicy().hasHeightForWidth())
        self.lstHazardLayers_2.setSizePolicy(sizePolicy)
        self.lstHazardLayers_2.setMinimumSize(QtCore.QSize(220, 100))
        self.lstHazardLayers_2.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstHazardLayers_2.setObjectName(_fromUtf8("lstHazardLayers_2"))
        item = QtGui.QListWidgetItem()
        self.lstHazardLayers_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.lstHazardLayers_2.addItem(item)
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setItalic(True)
        item.setFont(font)
        self.lstHazardLayers_2.addItem(item)
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setItalic(True)
        item.setFont(font)
        self.lstHazardLayers_2.addItem(item)
        self.gridLayout_16.addWidget(self.lstHazardLayers_2, 0, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_16)
        spacerItem56 = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem56)
        self.stackedWidget.addWidget(self.pgF3aLayerTOC)
        self.pgF3bLayerDisk = QtGui.QWidget()
        self.pgF3bLayerDisk.setObjectName(_fromUtf8("pgF3bLayerDisk"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.pgF3bLayerDisk)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_10 = QtGui.QLabel(self.pgF3bLayerDisk)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_12.addWidget(self.label_10)
        spacerItem57 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem57)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        spacerItem58 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem58, 0, 0, 1, 1)
        spacerItem59 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem59, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.pgF3bLayerDisk)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet(_fromUtf8("font-size:9pt;"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_11.addWidget(self.label_15, 0, 3, 1, 1)
        spacerItem60 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem60, 0, 4, 1, 1)
        self.tvBrowser = QtGui.QTreeView(self.pgF3bLayerDisk)
        self.tvBrowser.setObjectName(_fromUtf8("tvBrowser"))
        self.gridLayout_11.addWidget(self.tvBrowser, 0, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_11)
        spacerItem61 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem61)
        self.stackedWidget.addWidget(self.pgF3bLayerDisk)
        self.pgF8DisJointLayers = QtGui.QWidget()
        self.pgF8DisJointLayers.setObjectName(_fromUtf8("pgF8DisJointLayers"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.pgF8DisJointLayers)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        spacerItem62 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem62)
        self.label = QtGui.QLabel(self.pgF8DisJointLayers)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_15.addWidget(self.label)
        spacerItem63 = QtGui.QSpacerItem(20, 276, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem63)
        self.stackedWidget.addWidget(self.pgF8DisJointLayers)
        self.pgF13ParamsIF = QtGui.QWidget()
        self.pgF13ParamsIF.setObjectName(_fromUtf8("pgF13ParamsIF"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.pgF13ParamsIF)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        spacerItem64 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_19.addItem(spacerItem64)
        self.label_11 = QtGui.QLabel(self.pgF13ParamsIF)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_19.addWidget(self.label_11)
        spacerItem65 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_19.addItem(spacerItem65)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem66 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem66)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.targetFieldLabel = QtGui.QLabel(self.pgF13ParamsIF)
        self.targetFieldLabel.setObjectName(_fromUtf8("targetFieldLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.targetFieldLabel)
        self.targetFieldLineEdit = QtGui.QLineEdit(self.pgF13ParamsIF)
        self.targetFieldLineEdit.setObjectName(_fromUtf8("targetFieldLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.targetFieldLineEdit)
        self.roadTypeFieldLabel = QtGui.QLabel(self.pgF13ParamsIF)
        self.roadTypeFieldLabel.setObjectName(_fromUtf8("roadTypeFieldLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.roadTypeFieldLabel)
        self.roadTypeFieldLineEdit = QtGui.QLineEdit(self.pgF13ParamsIF)
        self.roadTypeFieldLineEdit.setObjectName(_fromUtf8("roadTypeFieldLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.roadTypeFieldLineEdit)
        self.affectedFieldLabel = QtGui.QLabel(self.pgF13ParamsIF)
        self.affectedFieldLabel.setObjectName(_fromUtf8("affectedFieldLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.affectedFieldLabel)
        self.affectedFieldLineEdit = QtGui.QLineEdit(self.pgF13ParamsIF)
        self.affectedFieldLineEdit.setObjectName(_fromUtf8("affectedFieldLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.affectedFieldLineEdit)
        self.affectedValueLabel = QtGui.QLabel(self.pgF13ParamsIF)
        self.affectedValueLabel.setObjectName(_fromUtf8("affectedValueLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.affectedValueLabel)
        self.affectedValueLineEdit = QtGui.QLineEdit(self.pgF13ParamsIF)
        self.affectedValueLineEdit.setObjectName(_fromUtf8("affectedValueLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.affectedValueLineEdit)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem67 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem67)
        self.verticalLayout_19.addLayout(self.horizontalLayout_3)
        spacerItem68 = QtGui.QSpacerItem(20, 284, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem68)
        self.stackedWidget.addWidget(self.pgF13ParamsIF)
        self.pgF19Run = QtGui.QWidget()
        self.pgF19Run.setObjectName(_fromUtf8("pgF19Run"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.pgF19Run)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        spacerItem69 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_18.addItem(spacerItem69)
        spacerItem70 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_18.addItem(spacerItem70)
        self.label_18 = QtGui.QLabel(self.pgF19Run)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_18.addWidget(self.label_18)
        spacerItem71 = QtGui.QSpacerItem(20, 414, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem71)
        self.stackedWidget.addWidget(self.pgF19Run)
        self.pgF20Run2 = QtGui.QWidget()
        self.pgF20Run2.setObjectName(_fromUtf8("pgF20Run2"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.pgF20Run2)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        spacerItem72 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_16.addItem(spacerItem72)
        self.label_20 = QtGui.QLabel(self.pgF20Run2)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_16.addWidget(self.label_20)
        spacerItem73 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_16.addItem(spacerItem73)
        self.progressBar = QtGui.QProgressBar(self.pgF20Run2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_16.addWidget(self.progressBar)
        self.textBrowser = QtGui.QTextBrowser(self.pgF20Run2)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_16.addWidget(self.textBrowser)
        spacerItem74 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_16.addItem(spacerItem74)
        self.stackedWidget.addWidget(self.pgF20Run2)
        self.pgF21GeneratePDF = QtGui.QWidget()
        self.pgF21GeneratePDF.setObjectName(_fromUtf8("pgF21GeneratePDF"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.pgF21GeneratePDF)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        spacerItem75 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem75)
        self.label_19 = QtGui.QLabel(self.pgF21GeneratePDF)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_17.addWidget(self.label_19)
        spacerItem76 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem76)
        self.textBrowser_2 = QtGui.QTextBrowser(self.pgF21GeneratePDF)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.verticalLayout_17.addWidget(self.textBrowser_2)
        spacerItem77 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem77)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem78 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem78)
        self.pushButton_3 = QtGui.QPushButton(self.pgF21GeneratePDF)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtGui.QPushButton(self.pgF21GeneratePDF)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.pgF21GeneratePDF)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem79 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem79)
        self.verticalLayout_17.addLayout(self.horizontalLayout)
        spacerItem80 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_17.addItem(spacerItem80)
        self.stackedWidget.addWidget(self.pgF21GeneratePDF)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pbnHelp = QtGui.QPushButton(WizardDialogBase)
        self.pbnHelp.setAutoDefault(False)
        self.pbnHelp.setObjectName(_fromUtf8("pbnHelp"))
        self.horizontalLayout_2.addWidget(self.pbnHelp)
        self.pbnCancel = QtGui.QPushButton(WizardDialogBase)
        self.pbnCancel.setAutoDefault(False)
        self.pbnCancel.setObjectName(_fromUtf8("pbnCancel"))
        self.horizontalLayout_2.addWidget(self.pbnCancel)
        spacerItem81 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem81)
        self.pbnBack = QtGui.QPushButton(WizardDialogBase)
        self.pbnBack.setAutoDefault(False)
        self.pbnBack.setObjectName(_fromUtf8("pbnBack"))
        self.horizontalLayout_2.addWidget(self.pbnBack)
        self.pbnNext = QtGui.QPushButton(WizardDialogBase)
        self.pbnNext.setAutoDefault(False)
        self.pbnNext.setDefault(False)
        self.pbnNext.setObjectName(_fromUtf8("pbnNext"))
        self.horizontalLayout_2.addWidget(self.pbnNext)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_8.setBuddy(self.treeClasses)
        self.label_7.setBuddy(self.lstUniqueValues)
        self.lblScale.setBuddy(self.leSource_scale)
        self.lblDate.setBuddy(self.leSource_date)
        self.lblSource.setBuddy(self.leSource)
        self.lblURL.setBuddy(self.leSource_url)
        self.lblTitle.setBuddy(self.leTitle)

        self.retranslateUi(WizardDialogBase)
        self.stackedWidget.setCurrentIndex(11)
        QtCore.QMetaObject.connectSlotsByName(WizardDialogBase)
        WizardDialogBase.setTabOrder(self.pbnCancel, self.pbnBack)
        WizardDialogBase.setTabOrder(self.pbnBack, self.pbnNext)
        WizardDialogBase.setTabOrder(self.pbnNext, self.lstCategories)
        WizardDialogBase.setTabOrder(self.lstCategories, self.lstSubcategories)
        WizardDialogBase.setTabOrder(self.lstSubcategories, self.lstUnits)
        WizardDialogBase.setTabOrder(self.lstUnits, self.lstFields)
        WizardDialogBase.setTabOrder(self.lstFields, self.lstUniqueValues)
        WizardDialogBase.setTabOrder(self.lstUniqueValues, self.treeClasses)
        WizardDialogBase.setTabOrder(self.treeClasses, self.leSource)
        WizardDialogBase.setTabOrder(self.leSource, self.leSource_url)
        WizardDialogBase.setTabOrder(self.leSource_url, self.leSource_scale)
        WizardDialogBase.setTabOrder(self.leSource_scale, self.leSource_date)
        WizardDialogBase.setTabOrder(self.leSource_date, self.leTitle)

    def retranslateUi(self, WizardDialogBase):
        WizardDialogBase.setWindowTitle(_translate("WizardDialogBase", "InaSAFE Keywords Creation Wizard...", None))
        self.lblMainTitle.setText(_translate("WizardDialogBase", "<html><head/><body><p><span style=\" font-size:22pt;\">Ina</span><span style=\" font-size:22pt; font-weight:600;\">SAFE</span><span style=\" font-size:22pt;\"> Wizard</span></p></body></html>", None))
        self.lblSubtitle.setText(_translate("WizardDialogBase", " Data-centric assessment...", None))
        self.lblStep.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblSelectCategory.setText(_translate("WizardDialogBase", "<html><head/><body><p>[placeholder]</p></body></html>", None))
        self.lblDescribeCategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblIconCategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblSelectSubcategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblDescribeSubcategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblIconSubcategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblSelectUnit.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblDescribeUnit.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblSelectField.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblDescribeField.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblClassify.setText(_translate("WizardDialogBase", "<html><head/><body><p>[placeholder]</p></body></html>", None))
        self.treeClasses.headerItem().setText(0, _translate("WizardDialogBase", "Classes", None))
        self.label_8.setText(_translate("WizardDialogBase", "Classified unique values", None))
        self.label_7.setText(_translate("WizardDialogBase", "Unclassified unique values", None))
        self.lblAggregation.setText(_translate("WizardDialogBase", "Please input these ratio attribute below for aggregation.", None))
        self.lblYouthRatioAttribute.setText(_translate("WizardDialogBase", "Youth ratio attribute", None))
        self.lblAdultRatioAttribute.setText(_translate("WizardDialogBase", "Adult ratio attribute", None))
        self.lblFemaleRatioDefault.setText(_translate("WizardDialogBase", "Female ratio default", None))
        self.lblAdultRatioDefault.setText(_translate("WizardDialogBase", "Adult ratio default", None))
        self.lblElderlyRatioAttribute.setText(_translate("WizardDialogBase", "Elderly ratio attribute", None))
        self.lblFemaleRatioAttribute.setText(_translate("WizardDialogBase", "Female ratio attribute", None))
        self.lblElderlyRatioDefault.setText(_translate("WizardDialogBase", "Elderly ratio default", None))
        self.lblYouthRatioDefault.setText(_translate("WizardDialogBase", "Youth ratio default", None))
        self.lblSelectSource.setText(_translate("WizardDialogBase", "<html><head/><body><p>Where does the data come from? You may want to write more or less short comment about its source.</p><p>This step is optional.</p></body></html>", None))
        self.lblScale.setText(_translate("WizardDialogBase", "Scale", None))
        self.lblDate.setText(_translate("WizardDialogBase", "Date", None))
        self.lblSource.setText(_translate("WizardDialogBase", "Source", None))
        self.lblURL.setText(_translate("WizardDialogBase", "URL", None))
        self.lblSelectTitle.setText(_translate("WizardDialogBase", "<html><head/><body><p>What is the title for this dataset? A title provides you with a way to give a dataset a more user friendly name than its filename. The title can include spaces. An example of a good title might be \'A flood in Jakarta\' (for a hazard layer) or \'People living in jakarta\' (for an exposure layer).</p></body></html>", None))
        self.lblTitle.setText(_translate("WizardDialogBase", "Title", None))
        self.lblSelectFunction.setText(_translate("WizardDialogBase", "<p>This wizard will guide you through the process of running an InaSAFE assessment. To start with you will need to choose what kind of analysis would you like to do?</p></body></html>", None))
        self.lblDescribeFunction.setText(_translate("WizardDialogBase", "TextLabel", None))
        self.lblSelectLayerOriginType.setText(_translate("WizardDialogBase", "<p>Please help us to find your <b>$CATEGORY</b> layer.</p><p>A hazard layer represents something that will impact the people or infrastructure in an area. For example a flood, earth quake, tsunami inundation are all different kinds of hazards.</p>", None))
        self.rbLayerFromCanvas.setText(_translate("WizardDialogBase", "I would like to use a layer already loaded in QGIS\n"
"(launches the $CATEGORY data registration wizard if needed)\n"
"", None))
        self.rbLayerFromDisk.setText(_translate("WizardDialogBase", "I would like to pick one of files from disk\n"
"(launches the $CATEGORY data registration wizard if needed)\n"
"", None))
        self.rbNoAggregation.setText(_translate("WizardDialogBase", "No thanks, I am happy to aggregate results for the entire analysis window", None))
        self.lblSelectHazardLayer.setText(_translate("WizardDialogBase", "<p>These are the layers currently loaded in QGIS. Please choose one HAZARD layer that you would like to use for your assessment.</p>", None))
        self.lblDescribeHazardLayer_2.setText(_translate("WizardDialogBase", "<html><head/><body><p><span style=\" font-weight:600;\">TITLE</span>: Tsunami di Maumere (Mw 8.1)<br/><span style=\" font-weight:600;\">CATEGORY</span>: hazard<br/><span style=\" font-weight:600;\">SUBCATEGORY</span>: tsunami<br/><span style=\" font-weight:600;\">UNIT</span>: m<br/><span style=\" font-weight:600;\">SOURCE</span>: AIFDR <br/><br/></p><p>... or (if no keywords):</p><p><span style=\" font-weight:600;\">This layer has no keywords assigned</span></p><p><span style=\" font-weight:600;\">SOURCE</span>: /mag/testdata/dummy/points.shp<br/><span style=\" font-weight:600;\">TYPE</span>: vector<br/><span style=\" font-weight:600;\">GEOMETRY TYPE</span>: point</p><p>In the next step you will be able to register this layer.</p></body></html>", None))
        __sortingEnabled = self.lstHazardLayers_2.isSortingEnabled()
        self.lstHazardLayers_2.setSortingEnabled(False)
        item = self.lstHazardLayers_2.item(0)
        item.setText(_translate("WizardDialogBase", "Hazard Layer 1", None))
        item = self.lstHazardLayers_2.item(1)
        item.setText(_translate("WizardDialogBase", "Hazard Layer 2", None))
        item = self.lstHazardLayers_2.item(2)
        item.setText(_translate("WizardDialogBase", "Layer without keywords 1", None))
        item = self.lstHazardLayers_2.item(3)
        item.setText(_translate("WizardDialogBase", "Layer without keywords 2", None))
        self.lstHazardLayers_2.setSortingEnabled(__sortingEnabled)
        self.label_10.setText(_translate("WizardDialogBase", "Please choose a file from disk. You can use the check box on the bottom to only display already registered files or all recognized datasources.", None))
        self.label_15.setText(_translate("WizardDialogBase", "<html><head/><body><p><span style=\" font-weight:600;\">TITLE</span>: Tsunami di Maumere (Mw 8.1)<br/><span style=\" font-weight:600;\">CATEGORY</span>: hazard<br/><span style=\" font-weight:600;\">SUBCATEGORY</span>: tsunami<br/><span style=\" font-weight:600;\">UNIT</span>: m<br/><span style=\" font-weight:600;\">SOURCE</span>: AIFDR <br/><br/></p><p>... or (if no keywords):</p><p><span style=\" font-weight:600;\">This layer has no keywords assigned</span></p><p><span style=\" font-weight:600;\">SOURCE</span>: /mag/testdata/dummy/points.shp<br/><span style=\" font-weight:600;\">TYPE</span>: vector<br/><span style=\" font-weight:600;\">GEOMETRY TYPE</span>: point</p><p>In the next step you will be able to register this layer.</p></body></html>", None))
        self.label.setText(_translate("WizardDialogBase", "The hazard layer and exposure layer don\'t intersect, i.e. they cover disjoint areas.\n"
"Please step back and select another layer.", None))
        self.label_11.setText(_translate("WizardDialogBase", "Please set impact functions parameters. (Please note the form below is a mockup)", None))
        self.targetFieldLabel.setText(_translate("WizardDialogBase", "Target field", None))
        self.targetFieldLineEdit.setText(_translate("WizardDialogBase", "flooded", None))
        self.roadTypeFieldLabel.setText(_translate("WizardDialogBase", "Road Type Field", None))
        self.roadTypeFieldLineEdit.setText(_translate("WizardDialogBase", "TYPE", None))
        self.affectedFieldLabel.setText(_translate("WizardDialogBase", "Affected Field", None))
        self.affectedFieldLineEdit.setText(_translate("WizardDialogBase", "affected", None))
        self.affectedValueLabel.setText(_translate("WizardDialogBase", "Affected Value", None))
        self.affectedValueLineEdit.setText(_translate("WizardDialogBase", "1", None))
        self.label_18.setText(_translate("WizardDialogBase", "It\'s all, now you can run your analysis.\n"
"\n"
"... There will be a summary here...\n"
"\n"
" Please click \"Run\".", None))
        self.label_20.setText(_translate("WizardDialogBase", "Running analysys...", None))
        self.textBrowser.setHtml(_translate("WizardDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here goes the existing progress report: <br /><br />Processing started...<br />Checking available memory...<br />Preparing hazard data...<br />Preparing exposure data...<br />Preparing aggregation layer...<br /></p></body></html>", None))
        self.label_19.setText(_translate("WizardDialogBase", "Analysis done.", None))
        self.textBrowser_2.setHtml(_translate("WizardDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here goes the existing report...</p></body></html>", None))
        self.pushButton_3.setText(_translate("WizardDialogBase", "Open in web browser", None))
        self.pushButton.setText(_translate("WizardDialogBase", "Generate PDF", None))
        self.pushButton_2.setText(_translate("WizardDialogBase", "Open in composer", None))
        self.pbnHelp.setText(_translate("WizardDialogBase", "Help", None))
        self.pbnCancel.setText(_translate("WizardDialogBase", "Cancel", None))
        self.pbnBack.setText(_translate("WizardDialogBase", "Back", None))
        self.pbnNext.setText(_translate("WizardDialogBase", "Next", None))

import resources_rc
