# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard_dialog_base.ui'
#
# Created: Thu Jun  5 14:15:19 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WizardDialogBase(object):
    def setupUi(self, WizardDialogBase):
        WizardDialogBase.setObjectName(_fromUtf8("WizardDialogBase"))
        WizardDialogBase.resize(797, 476)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WizardDialogBase.sizePolicy().hasHeightForWidth())
        WizardDialogBase.setSizePolicy(sizePolicy)
        WizardDialogBase.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WizardDialogBase.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(WizardDialogBase)
        self.verticalLayout.setContentsMargins(16, 16, 16, 4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblMainTitle = QtGui.QLabel(WizardDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMainTitle.sizePolicy().hasHeightForWidth())
        self.lblMainTitle.setSizePolicy(sizePolicy)
        self.lblMainTitle.setStyleSheet(_fromUtf8("font: 12pt;"))
        self.lblMainTitle.setObjectName(_fromUtf8("lblMainTitle"))
        self.horizontalLayout.addWidget(self.lblMainTitle)
        self.lblStep = QtGui.QLabel(WizardDialogBase)
        self.lblStep.setStyleSheet(_fromUtf8("font: 12pt;"))
        self.lblStep.setObjectName(_fromUtf8("lblStep"))
        self.horizontalLayout.addWidget(self.lblStep)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtGui.QFrame(WizardDialogBase)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.stackedWidget = QtGui.QStackedWidget(WizardDialogBase)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet(_fromUtf8("font-size:10pt"))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pg1Category = QtGui.QWidget()
        self.pg1Category.setStyleSheet(_fromUtf8(""))
        self.pg1Category.setObjectName(_fromUtf8("pg1Category"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pg1Category)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblSelectCategory = QtGui.QLabel(self.pg1Category)
        self.lblSelectCategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectCategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectCategory.setWordWrap(True)
        self.lblSelectCategory.setObjectName(_fromUtf8("lblSelectCategory"))
        self.verticalLayout_2.addWidget(self.lblSelectCategory)
        spacerItem2 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 0, 4, 1)
        self.lstCategories = QtGui.QListWidget(self.pg1Category)
        self.lstCategories.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstCategories.sizePolicy().hasHeightForWidth())
        self.lstCategories.setSizePolicy(sizePolicy)
        self.lstCategories.setMinimumSize(QtCore.QSize(220, 100))
        self.lstCategories.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstCategories.setObjectName(_fromUtf8("lstCategories"))
        self.gridLayout_6.addWidget(self.lstCategories, 0, 1, 4, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 2, 4, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 5, 4, 1)
        self.lblDescribeCategory = QtGui.QLabel(self.pg1Category)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeCategory.sizePolicy().hasHeightForWidth())
        self.lblDescribeCategory.setSizePolicy(sizePolicy)
        self.lblDescribeCategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDescribeCategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDescribeCategory.setWordWrap(True)
        self.lblDescribeCategory.setObjectName(_fromUtf8("lblDescribeCategory"))
        self.gridLayout_6.addWidget(self.lblDescribeCategory, 3, 3, 1, 1)
        self.lblIconCategory = QtGui.QLabel(self.pg1Category)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIconCategory.sizePolicy().hasHeightForWidth())
        self.lblIconCategory.setSizePolicy(sizePolicy)
        self.lblIconCategory.setMinimumSize(QtCore.QSize(192, 192))
        self.lblIconCategory.setMaximumSize(QtCore.QSize(192, 192))
        self.lblIconCategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblIconCategory.setScaledContents(True)
        self.lblIconCategory.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIconCategory.setObjectName(_fromUtf8("lblIconCategory"))
        self.gridLayout_6.addWidget(self.lblIconCategory, 2, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        spacerItem6 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.stackedWidget.addWidget(self.pg1Category)
        self.pg2Subcategory = QtGui.QWidget()
        self.pg2Subcategory.setStyleSheet(_fromUtf8(""))
        self.pg2Subcategory.setObjectName(_fromUtf8("pg2Subcategory"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pg2Subcategory)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblSelectSubcategory = QtGui.QLabel(self.pg2Subcategory)
        self.lblSelectSubcategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectSubcategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectSubcategory.setWordWrap(True)
        self.lblSelectSubcategory.setObjectName(_fromUtf8("lblSelectSubcategory"))
        self.verticalLayout_3.addWidget(self.lblSelectSubcategory)
        spacerItem7 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 2, 3, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 0, 3, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 5, 3, 1)
        self.lblDescribeSubcategory = QtGui.QLabel(self.pg2Subcategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeSubcategory.sizePolicy().hasHeightForWidth())
        self.lblDescribeSubcategory.setSizePolicy(sizePolicy)
        self.lblDescribeSubcategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDescribeSubcategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDescribeSubcategory.setWordWrap(True)
        self.lblDescribeSubcategory.setMargin(0)
        self.lblDescribeSubcategory.setObjectName(_fromUtf8("lblDescribeSubcategory"))
        self.gridLayout.addWidget(self.lblDescribeSubcategory, 2, 3, 1, 1)
        self.lblIconSubcategory = QtGui.QLabel(self.pg2Subcategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIconSubcategory.sizePolicy().hasHeightForWidth())
        self.lblIconSubcategory.setSizePolicy(sizePolicy)
        self.lblIconSubcategory.setMinimumSize(QtCore.QSize(192, 192))
        self.lblIconSubcategory.setMaximumSize(QtCore.QSize(192, 192))
        self.lblIconSubcategory.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblIconSubcategory.setScaledContents(True)
        self.lblIconSubcategory.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIconSubcategory.setWordWrap(True)
        self.lblIconSubcategory.setObjectName(_fromUtf8("lblIconSubcategory"))
        self.gridLayout.addWidget(self.lblIconSubcategory, 1, 3, 1, 1)
        self.lstSubcategories = QtGui.QListWidget(self.pg2Subcategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstSubcategories.sizePolicy().hasHeightForWidth())
        self.lstSubcategories.setSizePolicy(sizePolicy)
        self.lstSubcategories.setMinimumSize(QtCore.QSize(220, 0))
        self.lstSubcategories.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstSubcategories.setBaseSize(QtCore.QSize(0, 0))
        self.lstSubcategories.setObjectName(_fromUtf8("lstSubcategories"))
        self.gridLayout.addWidget(self.lstSubcategories, 0, 1, 3, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem11 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem11)
        self.stackedWidget.addWidget(self.pg2Subcategory)
        self.pg3Units = QtGui.QWidget()
        self.pg3Units.setObjectName(_fromUtf8("pg3Units"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pg3Units)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblSelectUnit = QtGui.QLabel(self.pg3Units)
        self.lblSelectUnit.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectUnit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectUnit.setWordWrap(True)
        self.lblSelectUnit.setObjectName(_fromUtf8("lblSelectUnit"))
        self.verticalLayout_4.addWidget(self.lblSelectUnit)
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem12)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem13 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 0, 0, 1, 1)
        self.lstUnits = QtGui.QListWidget(self.pg3Units)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstUnits.sizePolicy().hasHeightForWidth())
        self.lstUnits.setSizePolicy(sizePolicy)
        self.lstUnits.setMinimumSize(QtCore.QSize(220, 0))
        self.lstUnits.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstUnits.setBaseSize(QtCore.QSize(0, 0))
        self.lstUnits.setObjectName(_fromUtf8("lstUnits"))
        self.gridLayout_2.addWidget(self.lstUnits, 0, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 0, 2, 1, 1)
        self.lblDescribeUnit = QtGui.QLabel(self.pg3Units)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeUnit.sizePolicy().hasHeightForWidth())
        self.lblDescribeUnit.setSizePolicy(sizePolicy)
        self.lblDescribeUnit.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDescribeUnit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDescribeUnit.setWordWrap(True)
        self.lblDescribeUnit.setMargin(0)
        self.lblDescribeUnit.setObjectName(_fromUtf8("lblDescribeUnit"))
        self.gridLayout_2.addWidget(self.lblDescribeUnit, 0, 3, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 0, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        spacerItem16 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem16)
        self.stackedWidget.addWidget(self.pg3Units)
        self.pg4Field = QtGui.QWidget()
        self.pg4Field.setObjectName(_fromUtf8("pg4Field"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pg4Field)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lblSelectField = QtGui.QLabel(self.pg4Field)
        self.lblSelectField.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectField.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectField.setWordWrap(True)
        self.lblSelectField.setObjectName(_fromUtf8("lblSelectField"))
        self.verticalLayout_5.addWidget(self.lblSelectField)
        spacerItem17 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem17)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem18 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 1, 5, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 1, 0, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 1, 3, 1, 1)
        self.lstFields = QtGui.QListWidget(self.pg4Field)
        self.lstFields.setObjectName(_fromUtf8("lstFields"))
        self.gridLayout_3.addWidget(self.lstFields, 1, 1, 1, 2)
        self.lblDescribeField = QtGui.QLabel(self.pg4Field)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeField.sizePolicy().hasHeightForWidth())
        self.lblDescribeField.setSizePolicy(sizePolicy)
        self.lblDescribeField.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDescribeField.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblDescribeField.setWordWrap(True)
        self.lblDescribeField.setObjectName(_fromUtf8("lblDescribeField"))
        self.gridLayout_3.addWidget(self.lblDescribeField, 1, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        spacerItem21 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem21)
        self.stackedWidget.addWidget(self.pg4Field)
        self.pg5Categories = QtGui.QWidget()
        self.pg5Categories.setObjectName(_fromUtf8("pg5Categories"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.pg5Categories)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.lblClassify = QtGui.QLabel(self.pg5Categories)
        self.lblClassify.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblClassify.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblClassify.setWordWrap(True)
        self.lblClassify.setObjectName(_fromUtf8("lblClassify"))
        self.verticalLayout_14.addWidget(self.lblClassify)
        spacerItem22 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem22)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.treeClasses = QtGui.QTreeWidget(self.pg5Categories)
        self.treeClasses.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.treeClasses.setProperty("showDropIndicator", True)
        self.treeClasses.setDragEnabled(False)
        self.treeClasses.setDragDropOverwriteMode(False)
        self.treeClasses.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.treeClasses.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeClasses.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.treeClasses.setRootIsDecorated(False)
        self.treeClasses.setItemsExpandable(False)
        self.treeClasses.setExpandsOnDoubleClick(False)
        self.treeClasses.setObjectName(_fromUtf8("treeClasses"))
        self.treeClasses.header().setVisible(False)
        self.gridLayout_15.addWidget(self.treeClasses, 1, 5, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem23, 1, 4, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem24, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.pg5Categories)
        self.label_8.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_15.addWidget(self.label_8, 0, 5, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem25, 1, 2, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem26, 1, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.pg5Categories)
        self.label_7.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_15.addWidget(self.label_7, 0, 1, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem27, 1, 3, 1, 1)
        self.lstUniqueValues = QtGui.QListWidget(self.pg5Categories)
        self.lstUniqueValues.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lstUniqueValues.setDragEnabled(False)
        self.lstUniqueValues.setDragDropOverwriteMode(False)
        self.lstUniqueValues.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.lstUniqueValues.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lstUniqueValues.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lstUniqueValues.setObjectName(_fromUtf8("lstUniqueValues"))
        self.gridLayout_15.addWidget(self.lstUniqueValues, 1, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_15)
        spacerItem28 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_14.addItem(spacerItem28)
        self.stackedWidget.addWidget(self.pg5Categories)
        self.pg6Aggregations = QtGui.QWidget()
        self.pg6Aggregations.setEnabled(True)
        self.pg6Aggregations.setObjectName(_fromUtf8("pg6Aggregations"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.pg6Aggregations)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lblAggregation = QtGui.QLabel(self.pg6Aggregations)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblAggregation.setFont(font)
        self.lblAggregation.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblAggregation.setObjectName(_fromUtf8("lblAggregation"))
        self.verticalLayout_8.addWidget(self.lblAggregation)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblYouthRatioAttribute = QtGui.QLabel(self.pg6Aggregations)
        self.lblYouthRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblYouthRatioAttribute.setObjectName(_fromUtf8("lblYouthRatioAttribute"))
        self.gridLayout_7.addWidget(self.lblYouthRatioAttribute, 2, 0, 1, 1)
        self.dsbFemaleRatioDefault = QtGui.QDoubleSpinBox(self.pg6Aggregations)
        self.dsbFemaleRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.dsbFemaleRatioDefault.setMaximum(1.0)
        self.dsbFemaleRatioDefault.setSingleStep(0.01)
        self.dsbFemaleRatioDefault.setObjectName(_fromUtf8("dsbFemaleRatioDefault"))
        self.gridLayout_7.addWidget(self.dsbFemaleRatioDefault, 1, 1, 1, 1)
        self.cboYouthRatioAttribute = QtGui.QComboBox(self.pg6Aggregations)
        self.cboYouthRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.cboYouthRatioAttribute.setObjectName(_fromUtf8("cboYouthRatioAttribute"))
        self.gridLayout_7.addWidget(self.cboYouthRatioAttribute, 2, 1, 1, 1)
        self.lblAdultRatioAttribute = QtGui.QLabel(self.pg6Aggregations)
        self.lblAdultRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblAdultRatioAttribute.setObjectName(_fromUtf8("lblAdultRatioAttribute"))
        self.gridLayout_7.addWidget(self.lblAdultRatioAttribute, 4, 0, 1, 1)
        self.dsbAdultRatioDefault = QtGui.QDoubleSpinBox(self.pg6Aggregations)
        self.dsbAdultRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.dsbAdultRatioDefault.setMaximum(1.0)
        self.dsbAdultRatioDefault.setSingleStep(0.01)
        self.dsbAdultRatioDefault.setObjectName(_fromUtf8("dsbAdultRatioDefault"))
        self.gridLayout_7.addWidget(self.dsbAdultRatioDefault, 5, 1, 1, 1)
        self.cboElderlyRatioAttribute = QtGui.QComboBox(self.pg6Aggregations)
        self.cboElderlyRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.cboElderlyRatioAttribute.setObjectName(_fromUtf8("cboElderlyRatioAttribute"))
        self.gridLayout_7.addWidget(self.cboElderlyRatioAttribute, 6, 1, 1, 1)
        self.cboFemaleRatioAttribute = QtGui.QComboBox(self.pg6Aggregations)
        self.cboFemaleRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.cboFemaleRatioAttribute.setObjectName(_fromUtf8("cboFemaleRatioAttribute"))
        self.gridLayout_7.addWidget(self.cboFemaleRatioAttribute, 0, 1, 1, 1)
        self.lblFemaleRatioDefault = QtGui.QLabel(self.pg6Aggregations)
        self.lblFemaleRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblFemaleRatioDefault.setObjectName(_fromUtf8("lblFemaleRatioDefault"))
        self.gridLayout_7.addWidget(self.lblFemaleRatioDefault, 1, 0, 1, 1)
        self.lblAdultRatioDefault = QtGui.QLabel(self.pg6Aggregations)
        self.lblAdultRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblAdultRatioDefault.setObjectName(_fromUtf8("lblAdultRatioDefault"))
        self.gridLayout_7.addWidget(self.lblAdultRatioDefault, 5, 0, 1, 1)
        self.lblElderlyRatioAttribute = QtGui.QLabel(self.pg6Aggregations)
        self.lblElderlyRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblElderlyRatioAttribute.setObjectName(_fromUtf8("lblElderlyRatioAttribute"))
        self.gridLayout_7.addWidget(self.lblElderlyRatioAttribute, 6, 0, 1, 1)
        self.cboAdultRatioAttribute = QtGui.QComboBox(self.pg6Aggregations)
        self.cboAdultRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.cboAdultRatioAttribute.setObjectName(_fromUtf8("cboAdultRatioAttribute"))
        self.gridLayout_7.addWidget(self.cboAdultRatioAttribute, 4, 1, 1, 1)
        self.dsbYouthRatioDefault = QtGui.QDoubleSpinBox(self.pg6Aggregations)
        self.dsbYouthRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.dsbYouthRatioDefault.setMaximum(1.0)
        self.dsbYouthRatioDefault.setSingleStep(0.01)
        self.dsbYouthRatioDefault.setObjectName(_fromUtf8("dsbYouthRatioDefault"))
        self.gridLayout_7.addWidget(self.dsbYouthRatioDefault, 3, 1, 1, 1)
        self.lblFemaleRatioAttribute = QtGui.QLabel(self.pg6Aggregations)
        self.lblFemaleRatioAttribute.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblFemaleRatioAttribute.setObjectName(_fromUtf8("lblFemaleRatioAttribute"))
        self.gridLayout_7.addWidget(self.lblFemaleRatioAttribute, 0, 0, 1, 1)
        self.lblElderlyRatioDefault = QtGui.QLabel(self.pg6Aggregations)
        self.lblElderlyRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblElderlyRatioDefault.setObjectName(_fromUtf8("lblElderlyRatioDefault"))
        self.gridLayout_7.addWidget(self.lblElderlyRatioDefault, 7, 0, 1, 1)
        self.dsbElderlyRatioDefault = QtGui.QDoubleSpinBox(self.pg6Aggregations)
        self.dsbElderlyRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.dsbElderlyRatioDefault.setMaximum(1.0)
        self.dsbElderlyRatioDefault.setSingleStep(0.01)
        self.dsbElderlyRatioDefault.setObjectName(_fromUtf8("dsbElderlyRatioDefault"))
        self.gridLayout_7.addWidget(self.dsbElderlyRatioDefault, 7, 1, 1, 1)
        self.lblYouthRatioDefault = QtGui.QLabel(self.pg6Aggregations)
        self.lblYouthRatioDefault.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblYouthRatioDefault.setObjectName(_fromUtf8("lblYouthRatioDefault"))
        self.gridLayout_7.addWidget(self.lblYouthRatioDefault, 3, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem29)
        self.stackedWidget.addWidget(self.pg6Aggregations)
        self.pg7Source = QtGui.QWidget()
        self.pg7Source.setObjectName(_fromUtf8("pg7Source"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pg7Source)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lblSelectSource = QtGui.QLabel(self.pg7Source)
        self.lblSelectSource.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectSource.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectSource.setWordWrap(True)
        self.lblSelectSource.setObjectName(_fromUtf8("lblSelectSource"))
        self.verticalLayout_6.addWidget(self.lblSelectSource)
        spacerItem30 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem30)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblScale = QtGui.QLabel(self.pg7Source)
        self.lblScale.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblScale.setObjectName(_fromUtf8("lblScale"))
        self.gridLayout_4.addWidget(self.lblScale, 4, 1, 1, 1)
        self.lblDate = QtGui.QLabel(self.pg7Source)
        self.lblDate.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout_4.addWidget(self.lblDate, 6, 1, 1, 1)
        self.leSource_url = QtGui.QLineEdit(self.pg7Source)
        self.leSource_url.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leSource_url.setObjectName(_fromUtf8("leSource_url"))
        self.gridLayout_4.addWidget(self.leSource_url, 2, 2, 1, 1)
        self.leSource_date = QtGui.QLineEdit(self.pg7Source)
        self.leSource_date.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leSource_date.setObjectName(_fromUtf8("leSource_date"))
        self.gridLayout_4.addWidget(self.leSource_date, 6, 2, 1, 1)
        spacerItem31 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem31, 3, 2, 1, 1)
        self.leSource_scale = QtGui.QLineEdit(self.pg7Source)
        self.leSource_scale.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leSource_scale.setObjectName(_fromUtf8("leSource_scale"))
        self.gridLayout_4.addWidget(self.leSource_scale, 4, 2, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem32, 0, 0, 1, 1)
        self.lblSource = QtGui.QLabel(self.pg7Source)
        self.lblSource.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSource.setObjectName(_fromUtf8("lblSource"))
        self.gridLayout_4.addWidget(self.lblSource, 0, 1, 1, 1)
        self.leSource = QtGui.QLineEdit(self.pg7Source)
        self.leSource.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leSource.setObjectName(_fromUtf8("leSource"))
        self.gridLayout_4.addWidget(self.leSource, 0, 2, 1, 1)
        spacerItem33 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem33, 0, 3, 1, 1)
        self.lblURL = QtGui.QLabel(self.pg7Source)
        self.lblURL.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblURL.setObjectName(_fromUtf8("lblURL"))
        self.gridLayout_4.addWidget(self.lblURL, 2, 1, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem34, 1, 2, 1, 1)
        spacerItem35 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem35, 5, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        spacerItem36 = QtGui.QSpacerItem(20, 166, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem36)
        self.stackedWidget.addWidget(self.pg7Source)
        self.pg8Title = QtGui.QWidget()
        self.pg8Title.setObjectName(_fromUtf8("pg8Title"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.pg8Title)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lblSelectTitle = QtGui.QLabel(self.pg8Title)
        self.lblSelectTitle.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblSelectTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectTitle.setWordWrap(True)
        self.lblSelectTitle.setObjectName(_fromUtf8("lblSelectTitle"))
        self.verticalLayout_7.addWidget(self.lblSelectTitle)
        spacerItem37 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem37)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem38 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem38, 0, 0, 1, 1)
        self.lblTitle = QtGui.QLabel(self.pg8Title)
        self.lblTitle.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gridLayout_5.addWidget(self.lblTitle, 0, 1, 1, 1)
        self.leTitle = QtGui.QLineEdit(self.pg8Title)
        self.leTitle.setStyleSheet(_fromUtf8("font: 11pt \"Ubuntu\";"))
        self.leTitle.setObjectName(_fromUtf8("leTitle"))
        self.gridLayout_5.addWidget(self.leTitle, 0, 2, 1, 1)
        spacerItem39 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem39, 0, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        spacerItem40 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem40)
        self.stackedWidget.addWidget(self.pg8Title)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pbnHelp = QtGui.QPushButton(WizardDialogBase)
        self.pbnHelp.setAutoDefault(False)
        self.pbnHelp.setObjectName(_fromUtf8("pbnHelp"))
        self.horizontalLayout_2.addWidget(self.pbnHelp)
        self.pbnCancel = QtGui.QPushButton(WizardDialogBase)
        self.pbnCancel.setAutoDefault(False)
        self.pbnCancel.setObjectName(_fromUtf8("pbnCancel"))
        self.horizontalLayout_2.addWidget(self.pbnCancel)
        spacerItem41 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem41)
        self.pbnBack = QtGui.QPushButton(WizardDialogBase)
        self.pbnBack.setAutoDefault(False)
        self.pbnBack.setObjectName(_fromUtf8("pbnBack"))
        self.horizontalLayout_2.addWidget(self.pbnBack)
        self.pbnNext = QtGui.QPushButton(WizardDialogBase)
        self.pbnNext.setAutoDefault(False)
        self.pbnNext.setDefault(False)
        self.pbnNext.setObjectName(_fromUtf8("pbnNext"))
        self.horizontalLayout_2.addWidget(self.pbnNext)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_8.setBuddy(self.treeClasses)
        self.label_7.setBuddy(self.lstUniqueValues)
        self.lblScale.setBuddy(self.leSource_scale)
        self.lblDate.setBuddy(self.leSource_date)
        self.lblSource.setBuddy(self.leSource)
        self.lblURL.setBuddy(self.leSource_url)
        self.lblTitle.setBuddy(self.leTitle)

        self.retranslateUi(WizardDialogBase)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WizardDialogBase)
        WizardDialogBase.setTabOrder(self.pbnCancel, self.pbnBack)
        WizardDialogBase.setTabOrder(self.pbnBack, self.pbnNext)
        WizardDialogBase.setTabOrder(self.pbnNext, self.lstCategories)
        WizardDialogBase.setTabOrder(self.lstCategories, self.lstSubcategories)
        WizardDialogBase.setTabOrder(self.lstSubcategories, self.lstUnits)
        WizardDialogBase.setTabOrder(self.lstUnits, self.lstFields)
        WizardDialogBase.setTabOrder(self.lstFields, self.lstUniqueValues)
        WizardDialogBase.setTabOrder(self.lstUniqueValues, self.treeClasses)
        WizardDialogBase.setTabOrder(self.treeClasses, self.leSource)
        WizardDialogBase.setTabOrder(self.leSource, self.leSource_url)
        WizardDialogBase.setTabOrder(self.leSource_url, self.leSource_scale)
        WizardDialogBase.setTabOrder(self.leSource_scale, self.leSource_date)
        WizardDialogBase.setTabOrder(self.leSource_date, self.leTitle)

    def retranslateUi(self, WizardDialogBase):
        WizardDialogBase.setWindowTitle(QtGui.QApplication.translate("WizardDialogBase", "InaSAFE Keywords Creation Wizard...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMainTitle.setText(QtGui.QApplication.translate("WizardDialogBase", "InaSAFE Wizard...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStep.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectCategory.setText(QtGui.QApplication.translate("WizardDialogBase", "<html><head/><body><p>[placeholder]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescribeCategory.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIconCategory.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectSubcategory.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescribeSubcategory.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblIconSubcategory.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectUnit.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescribeUnit.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectField.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDescribeField.setText(QtGui.QApplication.translate("WizardDialogBase", "[placeholder]", None, QtGui.QApplication.UnicodeUTF8))
        self.lblClassify.setText(QtGui.QApplication.translate("WizardDialogBase", "<html><head/><body><p>[placeholder]</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeClasses.headerItem().setText(0, QtGui.QApplication.translate("WizardDialogBase", "Classes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("WizardDialogBase", "Classified unique values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("WizardDialogBase", "Unclassified unique values", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAggregation.setText(QtGui.QApplication.translate("WizardDialogBase", "Please input these ratio attribute below for aggregation.", None, QtGui.QApplication.UnicodeUTF8))
        self.lblYouthRatioAttribute.setText(QtGui.QApplication.translate("WizardDialogBase", "Youth ratio attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAdultRatioAttribute.setText(QtGui.QApplication.translate("WizardDialogBase", "Adult ratio attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFemaleRatioDefault.setText(QtGui.QApplication.translate("WizardDialogBase", "Female ratio default", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAdultRatioDefault.setText(QtGui.QApplication.translate("WizardDialogBase", "Adult ratio default", None, QtGui.QApplication.UnicodeUTF8))
        self.lblElderlyRatioAttribute.setText(QtGui.QApplication.translate("WizardDialogBase", "Elderly ratio attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFemaleRatioAttribute.setText(QtGui.QApplication.translate("WizardDialogBase", "Female ratio attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.lblElderlyRatioDefault.setText(QtGui.QApplication.translate("WizardDialogBase", "Elderly ratio default", None, QtGui.QApplication.UnicodeUTF8))
        self.lblYouthRatioDefault.setText(QtGui.QApplication.translate("WizardDialogBase", "Youth ratio default", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectSource.setText(QtGui.QApplication.translate("WizardDialogBase", "<html><head/><body><p>Where does the data come from? You may want to write more or less short comment about its source.</p><p>This step is optional.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScale.setText(QtGui.QApplication.translate("WizardDialogBase", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDate.setText(QtGui.QApplication.translate("WizardDialogBase", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSource.setText(QtGui.QApplication.translate("WizardDialogBase", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.lblURL.setText(QtGui.QApplication.translate("WizardDialogBase", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectTitle.setText(QtGui.QApplication.translate("WizardDialogBase", "<html><head/><body><p>What is the title for this dataset? A title provides you with a way to give a dataset a more user friendly name than its filename. The title can include spaces. An example of a good title might be \'A flood in Jakarta\' (for a hazard layer) or \'People living in jakarta\' (for an exposure layer).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitle.setText(QtGui.QApplication.translate("WizardDialogBase", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnHelp.setText(QtGui.QApplication.translate("WizardDialogBase", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnCancel.setText(QtGui.QApplication.translate("WizardDialogBase", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnBack.setText(QtGui.QApplication.translate("WizardDialogBase", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnNext.setText(QtGui.QApplication.translate("WizardDialogBase", "Next", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
