# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard_dialog_base.ui'
#
# Created: Fri Mar 14 17:22:29 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardDialogBase(object):
    def setupUi(self, WizardDialogBase):
        WizardDialogBase.setObjectName(_fromUtf8("WizardDialogBase"))
        WizardDialogBase.resize(797, 476)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WizardDialogBase.sizePolicy().hasHeightForWidth())
        WizardDialogBase.setSizePolicy(sizePolicy)
        WizardDialogBase.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WizardDialogBase.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(WizardDialogBase)
        self.verticalLayout.setContentsMargins(16, 16, 16, 4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblMainTitle = QtGui.QLabel(WizardDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMainTitle.sizePolicy().hasHeightForWidth())
        self.lblMainTitle.setSizePolicy(sizePolicy)
        self.lblMainTitle.setStyleSheet(_fromUtf8("font: 12pt;"))
        self.lblMainTitle.setObjectName(_fromUtf8("lblMainTitle"))
        self.horizontalLayout.addWidget(self.lblMainTitle)
        self.lblStep = QtGui.QLabel(WizardDialogBase)
        self.lblStep.setStyleSheet(_fromUtf8("font: 12pt;"))
        self.lblStep.setObjectName(_fromUtf8("lblStep"))
        self.horizontalLayout.addWidget(self.lblStep)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtGui.QFrame(WizardDialogBase)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.stackedWidget = QtGui.QStackedWidget(WizardDialogBase)
        self.stackedWidget.setStyleSheet(_fromUtf8("font-size:10pt"))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pg1Category = QtGui.QWidget()
        self.pg1Category.setStyleSheet(_fromUtf8(""))
        self.pg1Category.setObjectName(_fromUtf8("pg1Category"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pg1Category)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblSelectCategory = QtGui.QLabel(self.pg1Category)
        self.lblSelectCategory.setStyleSheet(_fromUtf8(""))
        self.lblSelectCategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectCategory.setWordWrap(True)
        self.lblSelectCategory.setObjectName(_fromUtf8("lblSelectCategory"))
        self.verticalLayout_2.addWidget(self.lblSelectCategory)
        spacerItem2 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblIconCategory = QtGui.QLabel(self.pg1Category)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIconCategory.sizePolicy().hasHeightForWidth())
        self.lblIconCategory.setSizePolicy(sizePolicy)
        self.lblIconCategory.setMinimumSize(QtCore.QSize(192, 192))
        self.lblIconCategory.setMaximumSize(QtCore.QSize(192, 192))
        self.lblIconCategory.setScaledContents(True)
        self.lblIconCategory.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIconCategory.setObjectName(_fromUtf8("lblIconCategory"))
        self.gridLayout_6.addWidget(self.lblIconCategory, 1, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 0, 3, 1, 1)
        self.lstCategories = QtGui.QListWidget(self.pg1Category)
        self.lstCategories.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstCategories.sizePolicy().hasHeightForWidth())
        self.lstCategories.setSizePolicy(sizePolicy)
        self.lstCategories.setMinimumSize(QtCore.QSize(220, 100))
        self.lstCategories.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstCategories.setObjectName(_fromUtf8("lstCategories"))
        self.gridLayout_6.addWidget(self.lstCategories, 0, 1, 3, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 2, 3, 1, 1)
        self.lblDescribeCategory = QtGui.QLabel(self.pg1Category)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeCategory.sizePolicy().hasHeightForWidth())
        self.lblDescribeCategory.setSizePolicy(sizePolicy)
        self.lblDescribeCategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDescribeCategory.setWordWrap(True)
        self.lblDescribeCategory.setObjectName(_fromUtf8("lblDescribeCategory"))
        self.gridLayout_6.addWidget(self.lblDescribeCategory, 0, 5, 3, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 6, 3, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 2, 3, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 0, 0, 3, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 4, 3, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        spacerItem9 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem9)
        self.stackedWidget.addWidget(self.pg1Category)
        self.pg2Subcategory = QtGui.QWidget()
        self.pg2Subcategory.setStyleSheet(_fromUtf8(""))
        self.pg2Subcategory.setObjectName(_fromUtf8("pg2Subcategory"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pg2Subcategory)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblSelectSubcategory = QtGui.QLabel(self.pg2Subcategory)
        self.lblSelectSubcategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectSubcategory.setWordWrap(True)
        self.lblSelectSubcategory.setObjectName(_fromUtf8("lblSelectSubcategory"))
        self.verticalLayout_3.addWidget(self.lblSelectSubcategory)
        spacerItem10 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem10)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblIconSubcategory = QtGui.QLabel(self.pg2Subcategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIconSubcategory.sizePolicy().hasHeightForWidth())
        self.lblIconSubcategory.setSizePolicy(sizePolicy)
        self.lblIconSubcategory.setMinimumSize(QtCore.QSize(192, 192))
        self.lblIconSubcategory.setMaximumSize(QtCore.QSize(192, 192))
        self.lblIconSubcategory.setScaledContents(True)
        self.lblIconSubcategory.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIconSubcategory.setWordWrap(True)
        self.lblIconSubcategory.setObjectName(_fromUtf8("lblIconSubcategory"))
        self.gridLayout.addWidget(self.lblIconSubcategory, 2, 3, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 0, 3, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 3, 3, 1, 1)
        self.lstSubcategories = QtGui.QListWidget(self.pg2Subcategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstSubcategories.sizePolicy().hasHeightForWidth())
        self.lstSubcategories.setSizePolicy(sizePolicy)
        self.lstSubcategories.setMinimumSize(QtCore.QSize(220, 0))
        self.lstSubcategories.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstSubcategories.setBaseSize(QtCore.QSize(0, 0))
        self.lstSubcategories.setObjectName(_fromUtf8("lstSubcategories"))
        self.gridLayout.addWidget(self.lstSubcategories, 0, 1, 4, 1)
        self.lblDescribeSubcategory = QtGui.QLabel(self.pg2Subcategory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeSubcategory.sizePolicy().hasHeightForWidth())
        self.lblDescribeSubcategory.setSizePolicy(sizePolicy)
        self.lblDescribeSubcategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDescribeSubcategory.setWordWrap(True)
        self.lblDescribeSubcategory.setMargin(0)
        self.lblDescribeSubcategory.setObjectName(_fromUtf8("lblDescribeSubcategory"))
        self.gridLayout.addWidget(self.lblDescribeSubcategory, 0, 5, 4, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 0, 4, 4, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 0, 2, 4, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 0, 0, 4, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 0, 6, 4, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem17 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem17)
        self.stackedWidget.addWidget(self.pg2Subcategory)
        self.pg3Units = QtGui.QWidget()
        self.pg3Units.setObjectName(_fromUtf8("pg3Units"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pg3Units)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblSelectUnit = QtGui.QLabel(self.pg3Units)
        self.lblSelectUnit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectUnit.setWordWrap(True)
        self.lblSelectUnit.setObjectName(_fromUtf8("lblSelectUnit"))
        self.verticalLayout_4.addWidget(self.lblSelectUnit)
        spacerItem18 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem18)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem19 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 0, 0, 1, 1)
        self.lstUnits = QtGui.QListWidget(self.pg3Units)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstUnits.sizePolicy().hasHeightForWidth())
        self.lstUnits.setSizePolicy(sizePolicy)
        self.lstUnits.setMinimumSize(QtCore.QSize(220, 0))
        self.lstUnits.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lstUnits.setBaseSize(QtCore.QSize(0, 0))
        self.lstUnits.setObjectName(_fromUtf8("lstUnits"))
        self.gridLayout_2.addWidget(self.lstUnits, 0, 1, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 0, 2, 1, 1)
        self.lblDescribeUnit = QtGui.QLabel(self.pg3Units)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDescribeUnit.sizePolicy().hasHeightForWidth())
        self.lblDescribeUnit.setSizePolicy(sizePolicy)
        self.lblDescribeUnit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDescribeUnit.setWordWrap(True)
        self.lblDescribeUnit.setMargin(0)
        self.lblDescribeUnit.setObjectName(_fromUtf8("lblDescribeUnit"))
        self.gridLayout_2.addWidget(self.lblDescribeUnit, 0, 3, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 0, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        spacerItem22 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem22)
        self.stackedWidget.addWidget(self.pg3Units)
        self.pg4Field = QtGui.QWidget()
        self.pg4Field.setObjectName(_fromUtf8("pg4Field"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pg4Field)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lblSelectField = QtGui.QLabel(self.pg4Field)
        self.lblSelectField.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectField.setWordWrap(True)
        self.lblSelectField.setObjectName(_fromUtf8("lblSelectField"))
        self.verticalLayout_5.addWidget(self.lblSelectField)
        spacerItem23 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem23)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem24 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem24, 1, 0, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem25, 1, 3, 1, 1)
        self.lstFields = QtGui.QListWidget(self.pg4Field)
        self.lstFields.setObjectName(_fromUtf8("lstFields"))
        self.gridLayout_3.addWidget(self.lstFields, 1, 1, 1, 2)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        spacerItem26 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem26)
        self.stackedWidget.addWidget(self.pg4Field)
        self.pg5Categories = QtGui.QWidget()
        self.pg5Categories.setObjectName(_fromUtf8("pg5Categories"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.pg5Categories)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.lblClassify = QtGui.QLabel(self.pg5Categories)
        self.lblClassify.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblClassify.setWordWrap(True)
        self.lblClassify.setObjectName(_fromUtf8("lblClassify"))
        self.verticalLayout_14.addWidget(self.lblClassify)
        spacerItem27 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_14.addItem(spacerItem27)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.treeClasses = QtGui.QTreeWidget(self.pg5Categories)
        self.treeClasses.setProperty("showDropIndicator", True)
        self.treeClasses.setDragEnabled(False)
        self.treeClasses.setDragDropOverwriteMode(False)
        self.treeClasses.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.treeClasses.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.treeClasses.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.treeClasses.setRootIsDecorated(False)
        self.treeClasses.setItemsExpandable(False)
        self.treeClasses.setExpandsOnDoubleClick(False)
        self.treeClasses.setObjectName(_fromUtf8("treeClasses"))
        self.treeClasses.header().setVisible(False)
        self.gridLayout_15.addWidget(self.treeClasses, 1, 5, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem28, 1, 4, 1, 1)
        spacerItem29 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem29, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.pg5Categories)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_15.addWidget(self.label_8, 0, 5, 1, 1)
        spacerItem30 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem30, 1, 2, 1, 1)
        spacerItem31 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem31, 1, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self.pg5Categories)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_15.addWidget(self.label_7, 0, 1, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem32, 1, 3, 1, 1)
        self.lstUniqueValues = QtGui.QListWidget(self.pg5Categories)
        self.lstUniqueValues.setDragEnabled(False)
        self.lstUniqueValues.setDragDropOverwriteMode(False)
        self.lstUniqueValues.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.lstUniqueValues.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lstUniqueValues.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lstUniqueValues.setObjectName(_fromUtf8("lstUniqueValues"))
        self.gridLayout_15.addWidget(self.lstUniqueValues, 1, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_15)
        spacerItem33 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_14.addItem(spacerItem33)
        self.stackedWidget.addWidget(self.pg5Categories)
        self.pg6Source = QtGui.QWidget()
        self.pg6Source.setObjectName(_fromUtf8("pg6Source"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pg6Source)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lblSelectSource = QtGui.QLabel(self.pg6Source)
        self.lblSelectSource.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectSource.setWordWrap(True)
        self.lblSelectSource.setObjectName(_fromUtf8("lblSelectSource"))
        self.verticalLayout_6.addWidget(self.lblSelectSource)
        spacerItem34 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem34)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.pg6Source)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.pg6Source)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 6, 1, 1, 1)
        self.leSource_url = QtGui.QLineEdit(self.pg6Source)
        self.leSource_url.setObjectName(_fromUtf8("leSource_url"))
        self.gridLayout_4.addWidget(self.leSource_url, 2, 2, 1, 1)
        self.leSource_date = QtGui.QLineEdit(self.pg6Source)
        self.leSource_date.setObjectName(_fromUtf8("leSource_date"))
        self.gridLayout_4.addWidget(self.leSource_date, 6, 2, 1, 1)
        spacerItem35 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem35, 3, 2, 1, 1)
        self.leSource_scale = QtGui.QLineEdit(self.pg6Source)
        self.leSource_scale.setObjectName(_fromUtf8("leSource_scale"))
        self.gridLayout_4.addWidget(self.leSource_scale, 4, 2, 1, 1)
        spacerItem36 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem36, 0, 0, 1, 1)
        self.lblSource = QtGui.QLabel(self.pg6Source)
        self.lblSource.setObjectName(_fromUtf8("lblSource"))
        self.gridLayout_4.addWidget(self.lblSource, 0, 1, 1, 1)
        self.leSource = QtGui.QLineEdit(self.pg6Source)
        self.leSource.setObjectName(_fromUtf8("leSource"))
        self.gridLayout_4.addWidget(self.leSource, 0, 2, 1, 1)
        spacerItem37 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem37, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.pg6Source)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 2, 1, 1, 1)
        spacerItem38 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem38, 1, 2, 1, 1)
        spacerItem39 = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem39, 5, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        spacerItem40 = QtGui.QSpacerItem(20, 166, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem40)
        self.stackedWidget.addWidget(self.pg6Source)
        self.pg7Title = QtGui.QWidget()
        self.pg7Title.setObjectName(_fromUtf8("pg7Title"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.pg7Title)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lblSelectTitle = QtGui.QLabel(self.pg7Title)
        self.lblSelectTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectTitle.setWordWrap(True)
        self.lblSelectTitle.setObjectName(_fromUtf8("lblSelectTitle"))
        self.verticalLayout_7.addWidget(self.lblSelectTitle)
        spacerItem41 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem41)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem42 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem42, 0, 0, 1, 1)
        self.lblTitle = QtGui.QLabel(self.pg7Title)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gridLayout_5.addWidget(self.lblTitle, 0, 1, 1, 1)
        self.leTitle = QtGui.QLineEdit(self.pg7Title)
        self.leTitle.setObjectName(_fromUtf8("leTitle"))
        self.gridLayout_5.addWidget(self.leTitle, 0, 2, 1, 1)
        spacerItem43 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem43, 0, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        spacerItem44 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem44)
        self.stackedWidget.addWidget(self.pg7Title)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pbnCancel = QtGui.QPushButton(WizardDialogBase)
        self.pbnCancel.setObjectName(_fromUtf8("pbnCancel"))
        self.horizontalLayout_2.addWidget(self.pbnCancel)
        spacerItem45 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem45)
        self.pbnBack = QtGui.QPushButton(WizardDialogBase)
        self.pbnBack.setObjectName(_fromUtf8("pbnBack"))
        self.horizontalLayout_2.addWidget(self.pbnBack)
        self.pbnNext = QtGui.QPushButton(WizardDialogBase)
        self.pbnNext.setObjectName(_fromUtf8("pbnNext"))
        self.horizontalLayout_2.addWidget(self.pbnNext)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_8.setBuddy(self.treeClasses)
        self.label_7.setBuddy(self.lstUniqueValues)
        self.label_2.setBuddy(self.leSource_scale)
        self.label_3.setBuddy(self.leSource_date)
        self.lblSource.setBuddy(self.leSource)
        self.label.setBuddy(self.leSource_url)
        self.lblTitle.setBuddy(self.leTitle)

        self.retranslateUi(WizardDialogBase)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(WizardDialogBase)
        WizardDialogBase.setTabOrder(self.pbnCancel, self.pbnBack)
        WizardDialogBase.setTabOrder(self.pbnBack, self.pbnNext)
        WizardDialogBase.setTabOrder(self.pbnNext, self.lstCategories)
        WizardDialogBase.setTabOrder(self.lstCategories, self.lstSubcategories)
        WizardDialogBase.setTabOrder(self.lstSubcategories, self.lstUnits)
        WizardDialogBase.setTabOrder(self.lstUnits, self.lstFields)
        WizardDialogBase.setTabOrder(self.lstFields, self.lstUniqueValues)
        WizardDialogBase.setTabOrder(self.lstUniqueValues, self.treeClasses)
        WizardDialogBase.setTabOrder(self.treeClasses, self.leSource)
        WizardDialogBase.setTabOrder(self.leSource, self.leSource_url)
        WizardDialogBase.setTabOrder(self.leSource_url, self.leSource_scale)
        WizardDialogBase.setTabOrder(self.leSource_scale, self.leSource_date)
        WizardDialogBase.setTabOrder(self.leSource_date, self.leTitle)

    def retranslateUi(self, WizardDialogBase):
        WizardDialogBase.setWindowTitle(_translate("WizardDialogBase", "InaSAFE Keywords Creation Wizard...", None))
        self.lblMainTitle.setText(_translate("WizardDialogBase", "InaSAFE Wizard...", None))
        self.lblStep.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblSelectCategory.setText(_translate("WizardDialogBase", "<html><head/><body><p>[placeholder]</p></body></html>", None))
        self.lblIconCategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblDescribeCategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblSelectSubcategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblIconSubcategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblDescribeSubcategory.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblSelectUnit.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblDescribeUnit.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblSelectField.setText(_translate("WizardDialogBase", "[placeholder]", None))
        self.lblClassify.setText(_translate("WizardDialogBase", "<html><head/><body><p>[placeholder]</p></body></html>", None))
        self.treeClasses.headerItem().setText(0, _translate("WizardDialogBase", "Classes", None))
        self.label_8.setText(_translate("WizardDialogBase", "Classified unique values", None))
        self.label_7.setText(_translate("WizardDialogBase", "Unclassified unique values", None))
        self.lblSelectSource.setText(_translate("WizardDialogBase", "<html><head/><body><p>Where does the data come from? You may want to write more or less short comment about its source.</p></body></html>", None))
        self.label_2.setText(_translate("WizardDialogBase", "Scale", None))
        self.label_3.setText(_translate("WizardDialogBase", "Date", None))
        self.lblSource.setText(_translate("WizardDialogBase", "Source", None))
        self.label.setText(_translate("WizardDialogBase", "URL", None))
        self.lblSelectTitle.setText(_translate("WizardDialogBase", "<html><head/><body><p>What is the title for this dataset? A title provides you with a way to give a dataset a more user friendly name than its filename. The title can include spaces. An example of a good title might be \'A flood in Jakarta\' (for a hazard layer) or \'People living in jakarta\' (for an exposure layer).</p></body></html>", None))
        self.lblTitle.setText(_translate("WizardDialogBase", "Title", None))
        self.pbnCancel.setText(_translate("WizardDialogBase", "Cancel", None))
        self.pbnBack.setText(_translate("WizardDialogBase", "Back", None))
        self.pbnNext.setText(_translate("WizardDialogBase", "Next", None))

import resources_rc
